- test/unit/ContentCard.test.js
> Include LocalVue and Bootstrap in tests

- README.md
- components/PageFooter.vue
- components/PageHeader.vue
- tests/unit/LoadingSpinner.spec.js
- tests/unit/PageFooter.spec.js
- tests/unit/PageHeader.spec.js
> Component unit tests

- components/browse/ContentCardSection.vue
- tests/unit/components/browse/ContentCardSection.spec.js
> Content card section tests

- plugins/europeana/search.js
- tests/unit/plugins/europeana/search.spec.js
Facets are returned by `search()` method in `.facets` property.
Example of structure of `search().facets`:
```js
{
TYPE: {
IMAGE: 33371202,
TEXT: 22845674,
VIDEO: 1137194,
SOUND: 699155,
'3D': 28460
}
}
```
> Return facets from search

- components/generic/PaginationNav.stories.js
- components/generic/PaginationNav.vue
- pages/search/index.vue
- tests/unit/components/generic/Pagination.spec.js
+ Storybook update
+ Unit tests
> Pagination component

- components/generic/PaginationNav.vue
- pages/search/index.vue
- plugins/europeana/search.js
- tests/features/search.feature
- tests/unit/components/generic/PaginationNav.spec.js
- tests/unit/plugins/europeana/search.spec.js
> Pagination component integration

- components/generic/PaginationNav.stories.js
- package-lock.json
- package.json
> Adding StoryRouter for components that use routing

- pages/search/index.vue
- plugins/europeana/search.js
- plugins/vue-filters.js
- tests/features/search/faceting.feature
- tests/features/search/pagination.feature
- tests/features/support/step-definitions.js
- tests/features/support/step-runners.js
- tests/unit/plugins/europeana/search.spec.js
> Country facet

- package-lock.json
- tests/features/config/cucumber.conf.js
* Fix issue in production with multiple versions of `compression` package
* Resolve outstanding vulnerability
> Full `npm update`

- pages/search/index.vue
- tests/features/search/querying.feature
Detect no facets before it triggers an error.
Rewrite E2E test
> Fix no results page

- components/browse/EntityDetails.vue
- plugins/europeana/entity.js
* Check if image URL ends with ".svg" (not just includes it)
* Remove attribution link if wikimedia image is broken
> Entity depiction tweaks

- components/browse/BrowseContentCard.vue
- components/browse/ContentCardSection.vue
- components/generic/ContentCard.vue
- components/generic/SmartLink.vue
- package-lock.json
- package.json
- pages/_.vue
- plugins/europeana/entity.js
- plugins/europeana/record.js
- tests/unit/components/browse/BrowseContentCard.spec.js
- tests/unit/components/generic/ContentCard.spec.js
- tests/unit/components/generic/SmartLink.spec.js
- tests/unit/components/record/WebResources.spec.js
- tests/unit/plugins/europeana/record.spec.js
* Adapt browse page content cards to be aware of entity collection data
* Refactor content card section component to render a child component for each browse card with its own computed properties
> Entity cards

- components/search/SearchFacet.vue
- components/search/SearchSelectedFacets.vue
- lang/en.js
- pages/search/index.vue
- plugins/europeana/search.js
- tests/features/search/faceting.feature
- tests/features/support/step-definitions.js
- tests/features/support/step-runners.js
- tests/unit/components/search/SearchFacet.spec.js
- tests/unit/components/search/SearchSelectedFacets.spec.js
- tests/unit/plugins/europeana/search.spec.js
- The facet component can handle radio buttons as well.
- The actual themes are hard-coded for now. 
- The theme facet is the first one in the column.
> Thematic collections facet

- .eslintrc.js
- components/record/LangMap.vue
- components/search/SearchResult.vue
- components/search/ViewToggles.vue
- pages/index.vue
- pages/search/index.vue
- plugins/europeana/record.js
- plugins/europeana/search.js
- store/footer.js
- tests/unit/components/record/LangMap.spec.js
https://eslint.org/docs/rules/eqeqeq
> Add eqeqeq eslint rule, and retrofit

- components/media/VideoPlayer.vue
- components/record/MediaPresentation.vue
- components/record/MetadataField.vue
- components/record/WebResources.stories.js
- components/record/WebResources.vue
- components/search/ViewToggles.vue
- lang/en.js
- pages/record/_.vue
- plugins/europeana/record.js
- tests/unit/components/record/WebResources.spec.js
Also stop sending specific fields from web resources in API response, and just send the full objects, but whitelist on the web resources component the fields to display.
> Set width and height on video element

- components/record/MediaPresentation.vue
- package-lock.json
- package.json
- plugins/oembed-parser/providers.json
- tests/unit/components/record/MediaPresentation.spec.js
Provider supported:
* soundcloud
* vimeo
* sketchfab
* youtube (but not really as no CORS support)
> Retrieve oEmbed from providers

- components/search/TierToggler.vue
- pages/search/index.vue
- plugins/europeana/search.js
- tests/features/search/contentTier.feature
- tests/unit/components/search/TierToggler.spec.js
* Remove some superfluous code
* Always set `page=1` in content tier toggle links
> Refactor content tier qf handling

- Dockerfile
- Jenkinsfile
- package-lock.json
- package.json
By adding dev dependency svg-url-loader.
Also:
* Update Node version to 12 in Dockerfile for Jenkins agent builds
* Move Storybook build/deploy stage after app deploy stage in Jenkins Pipeline
> Fix broken Storybook build

- plugins/oembed-parser/providers.json
- tests/unit/components/record/MediaPresentation.spec.js
> Remove Sketchfab and Dismarc from providers list

- .env.example
- components/PageHeader.vue
- tests/features/common/language-selector.feature
- tests/unit/components/PageHeader.spec.js
> Disable language selector by default

- components/browse/RichText.vue
- package-lock.json
- package.json
vue-markdown greatly increases the client bundle size
> Use marked instead of vue-markdown

- nuxt.config.js
- plugins/bootstrap-vue-plugins.js
To keep the bundled asset size down.
> Cherrypick Bootstrap Vue plugins

- package-lock.json
- package.json
- plugins/europeana/entity.js
Because client-side crypto is heavy
> Use md5 package instead of crypto

- plugins/europeana/search.js
> Replace use of Array.prototype.flat

- assets/scss/hero.scss
- assets/scss/licenses.scss
- components/browse/BrowseSections.vue
- components/generic/CiteAttribution.vue
- components/generic/CompareImageSlider.stories.js
- components/generic/CompareImageSlider.vue
- components/generic/HeroImage.vue
- components/generic/RightsStatement.vue
- lang/en.js
- tests/unit/components/generic/CiteAttribution.spec.js
- tests/unit/components/generic/CompareImageSlider.spec.js
- tests/unit/components/generic/HeroImage.spec.js
* Extract attribution into its own component for reuse in different places
* In the browse sections, detect imageComparison entries and display the image compare component for them
> Image comparison section

- pages/blog/index.vue
- pages/entity/_type/_.vue
- pages/exhibition/_exhibition/_chapter.vue
- pages/exhibition/_exhibition/index.vue
- pages/exhibitions/index.vue
- pages/search/index.vue
- plugins/europeana/search.js
- plugins/utils.js
- tests/features/pages/exhibitions-page.feature
- tests/features/support/step-runners.js
- tests/unit/plugins/europeana/search.spec.js
- tests/unit/plugins/utils.spec.js
Available at /exhibitions and via redirect from /exhibition
Will paginate when there are 20+ exhibitions
For now sorts by 'Created At' pending further refinement of publication process.
> Exhibition foyer

- .env.example
- components/PageHeader.vue
- tests/features/common/language-selector.feature
- tests/features/support/step-runners.js
- tests/unit/components/PageHeader.spec.js
> Remove feature toggle for language selector

- migrations/0012-entity-page-name-description.js
```shell
npx contentful space migration -e YOUR_CTF_ENV \
migrations/0012-entity-page-name-description.js
```
> Entity page: alter name field & add description

- migrations/0013-entityPage-primaryImageOfPage.js
```shell
npx contentful space migration -e YOUR_CTF_ENV \
migrations/0013-entityPage-primaryImageOfPage.js
```
> Entity page: add primaryImageOfPage

- README.md
* update maintainability badge
* remove test coverage badge
> Update CodeClimate badges

- pages/entity/_type/_.vue
- plugins/europeana/entity.js
- tests/unit/plugins/europeana/entity.spec.js
In user's language, and English if necessary
> Make two requests for entity page entries

- components/search/FacetDropdown.vue
- components/search/FacetFieldLabel.vue
- components/search/MoreFacetsDropdownOptions.vue
- components/search/SearchSelectedFacets.vue
- lang/en.js
- plugins/europeana/search.js
- plugins/i18n.js
- tests/features/search/faceting.feature
- tests/unit/components/search/FacetDropdown.spec.js
- tests/unit/components/search/FacetFieldLabel.spec.js
- tests/unit/components/search/MoreFacetsDropdown.spec.js
- tests/unit/components/search/MoreFacetsDropdownOptions.spec.js
- tests/unit/components/search/SearchSelectedFacets.spec.js
- tests/unit/plugins/europeana/search.spec.js
* Add technical image facets: IMAGE_ASPECTRATIO, IMAGE_SIZE, MIME_TYPE
* New component to act as SSOT for localising facet field labels
* Special derivation of MIME_TYPE labels unless translations exist
> Technical image facets

- package-lock.json
- package.json
* All Vue CLI packages should be [upgraded at once](https://cli.vuejs.org/migrating-from-v3/)
* It prevents running individual unit test scripts
> Downgrade @vue/cli-service

- assets/scss/cards.scss
- components/browse/BrowseContentCard.vue
- components/browse/ContentCardSection.vue
- components/entity/EntityCards.vue
- components/generic/ContentCard.vue
- layouts/default.vue
- tests/unit/components/entity/EntityCards.spec.js
- Updated styling of the related/entity cards
- Automated entity cards are now styles as related/entity cards
- Renamed the CSS "related-card" to "entity-card" and prop "isRelated" to "isEntity".
> Update styling of related cards

- migrations/0016-AutomatedRecordCard-multilingual.js
- Sets title, creator, provider to accept multiple languages.
> Migration for automated record card

- migrations/0017-create-imageGallery.js
> Make gallery identifier required

- .size-limit.json
- pages/gallery/_.vue
- pages/gallery/index.vue
- tests/features/pages/gallery-foyer-page.feature
- tests/features/pages/gallery-page.feature
- tests/features/support/pages.js
- Update gallery foyer to include links to pages
- Feature tests
> Creation of gallery page

- assets/scss/licenses.scss
- components/generic/SocialShare.vue
- components/record/MediaActionBar.vue
- lang/en.js
- pages/record/_.vue
- tests/unit/components/generic/SocialShare.spec.js
- tests/unit/components/record/MediaActionBar.spec.js
- Component for social share buttons, 
- Toggle in the action bar,
- og:title, og:type, og:image  and og:url on record pages
> Share a record

- pages/entity/_type/_.vue
i.e. only ever use curated descriptions
> Do not output entity collection descriptions

- assets/scss/cards.scss
- assets/scss/licenses.scss
- components/browse/BrowseSections.vue
- components/generic/ImageWithAttribution.vue
- pages/exhibition/_exhibition/_chapter.vue
- Attributions on image compares,
- Attributions in general,
- Word break on mini cards
> Exhibition styling

- store/entity.js
Else best bets are not applied.
> Remove quotes from entity prefLabel query

- components/search/FacetDropdown.vue
- plugins/europeana/search.js
- store/search.js
- tests/features/search/faceting.feature
- tests/unit/plugins/europeana/search.spec.js
Both from search results, and from reusability facet field display.
> Filter out uncategorised rights

- components/generic/ContentCard.vue
- tests/unit/components/generic/ContentCard.spec.js
* Set the label types in a data property
* Also detect blog.europeana.eu as a blog link
* Full unit tests for all supported types
> Atomise display label computation

- pages/exhibitions/_exhibition/index.vue
- pages/index.vue
On browse pages and exhibitions
> Conditional use of hero image for og:image

- assets/scss/form.scss
- components/PageNavigation.vue
following Ash's comment on the ticket https://europeana.atlassian.net/browse/EC-4369
> Active underline was overlapping nav bottom border

- assets/scss/form.scss
- components/PageHeader.vue
- components/PageNavigation.vue
- components/search/SearchForm.vue
> Initial above 992 style added

- components/PageHeader.vue
- components/entity/EntityDetails.vue
- components/item/MediaActionBar.vue
- layouts/default.vue
- tests/unit/components/entity/EntityDetails.spec.js
- follow correct accessibility rules
- added aria labels where needed
This took a lot longer than expected since I added aria labels to every button and link throughout the site and then found that axe accessibility tests were failing, most labels I added were later removed. But I have thoroughly checked the sites buttons and links and made sure they conform.
Also moved the cookie notifications and breadcrumbs in to the main landmark since elements can't be placed outside landmarks
> checked all links and buttons throughout the site 

- .env.example
- components/search/MoreFiltersDropdown.vue
- modules/apis/defaults.js
- store/collections/ww1.js
Feature toggle: `ENABLE_WW1_FULLTEXT_SEARCH=1`
> WW1 fulltext search

- pages/galleries/_.vue
- tests/features/pages/gallery-page.feature
- Use data from encoding field to find the social share image 
- Check presence of social share in feature test
> Social share icons on all gallery pages

- assets/scss/style.scss
- assets/scss/tabs.scss
- components/item/MetadataField.vue
- lang/en.js
- nuxt.config.js
- pages/item/_.vue
- Tabs contain metadata
- Styling of metadata has been updated, the metadata itself not
- Third optional tab to show transcriptions + notification
> Tabs for metadata and transcriptions

- components/item/SummaryInfo.stories.js
- components/item/SummaryInfo.vue
- lang/en.js
- pages/item/_.vue
- tests/unit/components/item/SummaryInfo.spec.js
New summary info component for the item page.
With storybook story and some unit tests.
> Title description box

- .size-limit.json
- pages/item-new/_.vue
- Alternative page, replace `item` in url with `item-new`
- New grid, with some components
- Todos were new components have to be added, or to indicate any other change
> New item page: alternative page + grid

- components/generic/PaginationNav.vue
- components/search/SearchInterface.vue
- pages/blog/index.vue
- pages/collections/_type/index.vue
- pages/exhibitions/index.vue
- pages/galleries/index.vue
- tests/features/pages/entity-page.feature
- tests/features/search/pagination.feature
* Reusing existing route & query, just overriding page param
* Also move check whether to display pagination nav into component
> Default pagination nav link gen

- components/generic/ContentCard.vue
- components/item/ItemPreviewCard.vue
- components/item/ItemPreviewCardGroup.vue
- components/search/SearchInterface.vue
- tests/unit/components/item/ItemPreviewCardGroup.spec.js
* FKA search results component
* Footer named slot in content card component, used by item preview card component to slot in the user buttons
> Item preview card group component

- components/account/UserSets.vue
- lang/en.js
- pages/account/index.vue
> Informative messages for absence of likes/public/private collections

- modules/axios-logger/index.js
- modules/axios-logger/templates/plugin.js
- modules/axios-logger/templates/store.js
- modules/contentful-graphql/plugin.js
- nuxt.config.js
* Not registered on axios global request interceptors
* Registered on Contentful GraphQL axios instance
> Axios logger module

- modules/contentful-graphql/queries/browse-page.graphql
> Graphql update for hero image type check

- layouts/default.vue
To speed up initial response times.
> Do not fetch on server

- .github/workflows/ci.yml
- docker/stack/nightwatch/Dockerfile
- docker/stack/nightwatch/package-lock.json
- docker/stack/nightwatch/package.json
- docker/stack/nightwatch/percy.js
See: https://docs.percy.io/docs/migrating-to-percy-cli
> Migrate from @percy/agent to @percy/cli

- store/entity.js
- store/search.js
- store/set.js
- tests/unit/store/search.spec.js
- tests/unit/store/set.spec.js
To fix `'state' is already declared in the upper scope.` code smells flagged by SonarCloud.
> Export default from store modules

- components/item/ItemHero.vue
- pages/iiif/index.vue
Re: https://sonarcloud.io/project/issues?id=europeana_portal.js&issues=AXhtpkFeHiOtkrFrPzfh&open=AXhtpkFeHiOtkrFrPzfh
> Only respond to updateDownloadLink from same origin

- src/components/generic/CookieDisclaimer.vue
- src/lang/en.js
- src/layouts/default.vue
- tests/features/common/language-selector.feature
- tests/features/common/layout.feature
- tests/features/config/cucumber.conf.js
- tests/features/pages/home-page.feature
- tests/features/support/step-runners.js
- tests/unit/components/generic/CookieDisclaimer.spec.js
- tests/unit/layouts/default.spec.js
Reverts europeana/portal.js#1060
> Revert "chore: remove CookieDisclaimer code"

- src/components/PageNavigation.vue
to react to changes in localisation
> computed nav links

- src/components/generic/CookieDisclaimer.vue
To be in front of feedback widget
> Increase cookie disclaimer z-index

- src/components/search/ViewToggles.vue
- tests/unit/components/search/ViewToggles.spec.js
> Remove superfluous click event handler

- tests/e2e/docker/nightwatch/package-lock.json
- tests/e2e/docker/nightwatch/package.json
- tests/e2e/docker/nightwatch/support/step-runners.js
Also start validating against WCAG 2.1 Level A & AA Rules
> Update nightwatch-accessibility for axe 4

- src/assets/scss/cards.scss
- src/components/generic/DownloadButton.vue
- src/components/generic/RelatedChip.vue
- src/pages/contentful/entity-harvester/index.vue
- tests/size/.size-limit.json
- tests/unit/components/generic/RelatedChip.spec.js
+ Fixed typo,
+ Fixed linting errors
> Add Matomo event for related collections

- src/pages/collections/_type/_.vue
> refactor: stop using axios.all

- .sonarcloud.properties
- package-lock.json
- package.json
for upstream fixes to issues affecting refresh of oauth access tokens
> chore: bump axios to ^0.21.4

- package-lock.json
- src/assets/scss/media.scss
- tests/e2e/features/ZZ-finally/memory-usage.feature
... and tweak CSS to maintain vertical placement of swiper pagination buttons.
> chore: package lock update

- src/components/account/UserSets.vue
- src/components/generic/TextHighlighter.vue
- src/components/item/ItemPreviewCard.vue
- src/components/item/ItemPreviewCardGroup.vue
- src/components/recommendation/RecommendationButtons.vue
- src/components/search/SearchForm.vue
- src/components/search/SearchInterface.vue
- src/components/search/SearchQueryOptions.vue
- src/pages/account/index.vue
- src/pages/item/_.vue
- src/pages/set/_.vue
- tests/unit/components/account/UserSets.spec.js
- tests/unit/components/item/ItemPreviewCardGroup.spec.js
- tests/unit/components/recommendation/RecommendationButtons.spec.js
- tests/unit/components/search/SearchQueryOptions.spec.js
as it is only needed for two-way data bindings.
> refactor: resolve inappropriate use of v-model

- nuxt.config.js
- package-lock.json
- package.json
- src/components/item/SummaryInfo.vue
- src/components/search/SearchInterface.vue
- src/components/set/SetRecommendations.vue
- src/layouts/default.vue
- src/pages/collections/_type/_.vue
- src/pages/item/_.vue
- src/pages/search/index.vue
- src/pages/set/_.vue
- src/plugins/ab-testing.js
- src/plugins/europeana/record.js
- src/plugins/features.js
- tests/unit/components/item/ItemHero.spec.js
- tests/unit/components/item/MetadataField.spec.js
- tests/unit/components/item/SummaryInfo.spec.js
- tests/unit/components/search/FacetDropdown.spec.js
- tests/unit/components/search/SearchInterface.spec.js
- tests/unit/components/search/SideDateFilter.spec.js
- tests/unit/components/set/SetRecommendations.spec.js
- tests/unit/layouts/default.spec.js
- tests/unit/pages/blog/_.spec.js
- tests/unit/pages/collections/type/_.spec.js
- tests/unit/pages/index.spec.js
- tests/unit/pages/item/_.spec.js
- tests/unit/pages/set/_.spec.js
- tests/unit/plugins/europeana/record.spec.js
1. Add `features` function to nuxt.config.js to DRY up feature-toggle detection
2. Inject `features` plugin for more concise feature-toggle lookup in views, like `this.$features.sideFilters`
> refactor: features plugin

- src/pages/collections/_type/_.vue
> fix: watch and store search override changes

- src/components/generic/CiteAttribution.vue
- src/components/generic/CompareImageSlider.vue
- styleguide/styleguide.root.js
- tests/size/.size-limit.json
- tests/unit/components/generic/CompareImageSlider.spec.js
> test: CompareImageSlider unit tests

- docs/style/BootstrapVueBadge.md
- docs/style/BootstrapVueButton.md
- docs/style/FontIcons.md
- src/assets/scss/icons.scss
- styleguide.config.cjs
- styleguide/style.scss
Also move Bootstrap Vue custom style documentation to docs directory.
> docs: document font icons in docs directory

- .github/workflows/ci.yml
For JIRA ticket number, and preview deployment
> chore: automate PR comments

- src/assets/scss/form.scss
- src/assets/scss/tooltip.scss
- src/components/item/MetadataOriginLabel.vue
- src/components/search/SideFacetDropdown.vue
- src/components/search/SideFilters.vue
- src/components/search/SideSwitchFilter.vue
- src/lang/en.js
- tests/size/.size-limit.json
- tests/unit/components/search/SideFilters.spec.js
- tests/unit/components/search/SideSwitchFilter.spec.js
Used at first for the API metadata/fulltext option.
> feat: add side switch filter component

- Dockerfile
- package-lock.json
- package.json
> chore: max Node version 16.13

- src/assets/scss/dropdown.scss
- src/components/search/SideFacetDropdown.vue
- src/lang/en.js
- src/plugins/europeana/search.js
- tests/e2e/features/search/faceting.feature
- tests/unit/components/search/SideFacetDropdown.spec.js
> feat: load all facet values

- package-lock.json
- package.json
Resolving https://github.com/europeana/portal.js/security/dependabot/3
> chore: vue-styleguidist 4.44.27

- src/components/account/UserSets.vue
- src/components/set/AddItemToSetModal.vue
- src/store/set.js
- tests/unit/store/set.spec.js
> feat: supply offset and type for user set default thumbnails

- src/components/item/AwesomeSwiper.vue
- src/components/item/ItemHero.vue
- src/components/item/MediaCard.vue
- src/components/item/MediaCardImage.vue
- src/pages/item/_.vue
- src/plugins/media.js
- tests/unit/plugins/media.spec.js
> feat: offset thumbnail colour on item media card

- src/cachers/items/recent.js
Rare scenario, but possible in the case of active reindexing.
> fix: handle fewer than 4 datasets

- src/assets/scss/table.scss
- src/cachers/collections/organisations.js
- src/cachers/collections/organisations/featured.js
- src/components/entity/EntityHeader.vue
- src/components/entity/EntityTable.vue
- src/lang/en.js
- tests/unit/cachers/collections/organisations.spec.js
- tests/unit/cachers/collections/organisations/featured.spec.js
- tests/unit/components/entity/EntityTable.spec.js
* Display of both native name and English name
* Updated styling of table
> New design for organisations hub page

- src/migrations/0078-switch-disabled-single-line-to-app.cjs
- src/pages/contentful/disabled-single-line/index.vue
- tests/unit/pages/contentful/disabled-single-line/index.spec.js
- tests/unit/utils.js
Adds a new migration that needs to be run after the app is available in contentful.
> feat: disabled single line text app for contentful

- package-lock.json
- package.json
- src/pages/galleries/_.vue
- src/pages/set/_.vue
- tests/size/.size-limit.json
- tests/unit/pages/galleries/_set.spec.js
- tests/unit/pages/set/_.spec.js
Because the Set API does not, and yet it returns the requested ID in its API response, which we in turn output on the error display.
> security: validate set IDs

- packages/portal/nuxt.config.js
- packages/portal/src/plugins/europeana/annotation.js
- packages/portal/src/plugins/europeana/entity-management.js
- packages/portal/src/plugins/europeana/entity.js
- packages/portal/src/plugins/europeana/iiif.js
- packages/portal/src/plugins/europeana/newspaper.js
- packages/portal/src/plugins/europeana/recommendation.js
- packages/portal/src/plugins/europeana/record.js
- packages/portal/src/plugins/europeana/set.js
Plus: stop defaulting base URL constants to env vars.
> chore: entity mgmt service fallback URL

- .github/workflows/ci.yml
- .stylelintrc.cjs
- package-lock.json
- package.json
To get stylelint to analyse .vue files
> chore: install postcss-scss

- packages/portal/src/lang/it.js
Automated translation updates by [Lokalise workflow](https://github.com/europeana/portal.js/blob/master/.github/workflows/lokalise.yml).
> l10n: update translations

- .github/workflows/ci.yml
To speed up builds of future PR images with common, cached layers.
> chore: add pr tag to pull request images

- .github/workflows/ci.yml
- packages/portal/jest.config.js
See: https://github.com/vuejs/vue-jest/issues/422
> chore: use v8 coverageProvider for Jest

- packages/portal/src/components/set/DeleteSetModal.vue
- packages/portal/src/components/set/SetFormModal.vue
- packages/portal/src/pages/galleries/_.vue
- packages/portal/tests/size/.size-limit.json
- packages/portal/tests/unit/components/set/SetFormModal.spec.js
* prevent gallery deletion by publishers for sets which they are not the owner of
* also included prevent saving galleries without titles where the only existing title is removed by the user.
> feat: prevent deletion by publishers

- packages/portal/src/features/toggles.js
- packages/portal/src/pages/collections/_type/_.vue
- packages/portal/src/plugins/europeana/themes.js
- packages/portal/tests/size/.size-limit.json
- packages/portal/tests/unit/pages/collections/_type/_.spec.js
- packages/portal/tests/unit/plugins/europeana/themes.spec.js
- packages/portal/tests/unit/utils.js
Enable with `ENABLE_THEME_PAGES=1`
NB: destination URLs like /themes/art do not yet exist.
> chore: redirect to new theme page URLs

- packages/portal/src/plugins/europeana/utils.js
- packages/portal/tests/unit/plugins/europeana/utils.spec.js
> fix: prevent proxying headers to APIs

- .github/workflows/ci.yml
- .github/workflows/recycling.yml
- .github/workflows/styleguide.yml
GHA now supports not just secrets, but also [variables](https://github.com/europeana/portal.js/settings/variables/actions), so let's move those hard-coded workflow values there.
> chore: use GitHub Actions workflow variables

- packages/portal/src/components/item/ItemPinButton.vue
- packages/portal/src/components/item/ItemPinModal.vue
- packages/portal/src/components/set/SetFormModal.vue
- packages/portal/src/lang/en.js
- packages/portal/src/mixins/europeana/entities/entityBestItemsSet.js
- packages/portal/src/pages/galleries/_.vue
- packages/portal/src/store/entity.js
- packages/portal/tests/unit/components/item/ItemPinButton.spec.js
- packages/portal/tests/unit/components/item/ItemPinModal.spec.js
* introduce a new mixin for the creation of EntityBestItemsSet sets when required for pinning
* constructs localised set titles from all of the available entity prefLabels
* make ItemPinButton and ItemPinModal use this mixin
* fixes pinning from ItemPinModal when no English prefLabel is available
> feat: localising EntityBestItemsSet mixin

- packages/portal/src/components/generic/LanguageSelector.vue
- packages/portal/tests/unit/components/generic/LanguageSelector.spec.js
To prevent no results on localised index pages where results are localised.
> remove pagination in LanguageSelector

- .github/workflows/ci.yml
- packages/portal/src/cachers/index.js
- packages/portal/src/features/index.js
- packages/portal/src/plugins/apis.js
To check they can be loaded in Node.js
> chore: add CI job to list cachers

- packages/portal/src/pages/iiif/index.vue
- packages/portal/tests/unit/pages/iiif/index.spec.js
> feat: media proxy for IIIF

- tests/e2e/visual/pages.feature
remove duplicate screenshot; add wait for gallery grid alignment
> chore: percy consistency

- packages/portal/src/components/iiif/IIIFViewer.vue
> fix: null check for IIIF service profile

- packages/portal/src/components/metadata/MetadataBox.vue
- packages/portal/src/lang/en.js
- packages/portal/src/pages/item/_.vue
- packages/portal/tests/unit/pages/item/_.spec.js
Reverts europeana/portal.js#2004
Reverted, pending data issues being resolved on some records with existing plain text transcription annotations
> Revert "feat: filter item page annotation motivations"

- packages/portal/src/plugins/europeana/search.js
So that search results are localised correctly.
> fix: read locale from context

- packages/portal/src/server-middleware/api/index.js
Because it's not necessary and adds needless overhead to the request processing.
> refactor: load nuxt runtime config without middleware

- package-lock.json
- packages/portal/package.json
- packages/portal/src/components/landing/LandingAutomatedCardGroup.vue
- packages/portal/src/components/landing/LandingPage.vue
- packages/portal/src/components/landing/LandingSubSection.vue
- packages/portal/src/modules/contentful/index.js
* revert client-only workarounds for landing page SSR issue
> chore: use lodash camelcase

- packages/portal/src/components/browse/BrowseSections.vue
- packages/portal/src/components/embed/EmbedHTML.vue
- packages/portal/src/components/landing/LandingEmbed.vue
- packages/portal/src/components/landing/LandingPage.vue
- packages/portal/tests/unit/components/embed/EmbedHTML.spec.js
- tests/e2e/docker/nightwatch/support/pages.js
- tests/e2e/features/pages/share-your-data-page.feature
* set title on embed HTML iframe for a11y
> chore: e2e test "share your data" page

- packages/portal/src/components/browse/BrowseSections.vue
- packages/portal/src/components/landing/LandingPage.vue
- packages/portal/src/components/landing/LandingSubSection.vue
- packages/portal/src/mixins/contentful.js
- packages/portal/tests/unit/components/landing/LandingPage.spec.js
- packages/portal/tests/unit/components/landing/LandingSubSection.spec.js
- packages/portal/tests/unit/mixins/contentful.spec.js
* with single method to determine if entry matches given content type, by __typename property
* update components to use this mixin
> refactor: create contentful mixin

- packages/portal/src/components/DS4CH/DS4CHLandingHero.vue
- packages/portal/src/components/DS4CH/DS4CHPageFooter.vue
- packages/portal/src/components/DS4CH/DS4CHPageHeader.vue
- packages/portal/src/components/DS4CH/DS4CHPageNavigation.vue
- packages/portal/src/components/feedback/FeedbackWidget.vue
- packages/portal/src/components/landing/LandingCallToAction.vue
- packages/portal/src/components/landing/LandingIllustrationGroup.vue
- packages/portal/src/components/landing/LandingImageCard.vue
- packages/portal/src/components/landing/LandingPage.vue
- packages/portal/src/components/landing/LandingSubSection.vue
- packages/portal/src/components/page/PageFooter.vue
- packages/portal/src/lang/en.js
- packages/portal/tests/unit/components/feedback/FeedbackWidget.spec.js
- packages/portal/tests/unit/components/page/PageFooter.spec.js
- packages/style/scss/DS4CH/style.scss
* mv feedback widget to own component
* add new component to both main page footer and ds4ch footer
> chore: add feedback widget to ds4ch footer

- packages/portal/src/components/DS4CH/DS4CHPageFooter.vue
- packages/portal/src/components/generic/LinkGroup.vue
- packages/portal/src/components/page/PageFooter.vue
- packages/style/scss/footer.scss
- Moves footer link group styles to LinkGroup
- Adds LinkGroup to DS4CHPageFooter
- Adds a visually hidden h2 for correct heading structure and easier nav for keyboard users
> chore: DS footer links

- packages/portal/src/plugins/europeana/fulltext.js
- packages/portal/tests/unit/components/search/SearchInterface.spec.js
- tests/e2e/docker/docker-compose.yml
- tests/e2e/docker/nginx/conf.d/default.conf
to official URL: https://api.europeana.eu/fulltext
> chore: update fulltext Record API URL

- packages/portal/src/components/stories/StoriesInterface.vue
- packages/portal/src/modules/contentful/queries/stories-minimal.graphql
- packages/portal/src/modules/contentful/queries/stories-page.graphql
- packages/portal/src/pages/stories/index.vue
- packages/portal/tests/unit/components/stories/StoriesInterface.spec.js
* exclude the featured story from the main display of stories, so as not to duplicate
* include/exclude the featured story based on applied tags
* don't feature the story if not in the current UI language
> feat: featured story display

- packages/contentful/migrations/0139-update-story-hero-help-text.cjs
- packages/portal/src/components/story/StoryPost.vue
- packages/portal/tests/unit/components/story/StoryHero.spec.js
- packages/portal/tests/unit/components/story/StoryPost.spec.js
To be more selective with when to apply the new story header.
> chore: update immersive story hero image requirement to 1000px

- packages/portal/src/components/content/ContentHubPage.vue
- packages/portal/src/components/home/HomePage.vue
- packages/portal/src/components/story/StoryPost.vue
- packages/portal/src/mixins/exhibitionChapters.js
- packages/portal/src/mixins/pageMeta.js
- packages/portal/src/pages/exhibitions/_exhibition/_chapter.vue
- packages/portal/src/pages/exhibitions/_exhibition/index.vue
- packages/portal/src/pages/exhibitions/index.vue
- packages/portal/src/pages/galleries/index.vue
- packages/portal/src/pages/index.vue
- packages/portal/src/pages/stories/_.vue
- packages/portal/src/pages/stories/index.vue
- packages/portal/src/pages/themes/_.vue
- packages/portal/src/pages/themes/index.vue
- packages/portal/tests/unit/components/home/HomePage.spec.js
- packages/portal/tests/unit/mixins/pageMeta.spec.js
- packages/portal/tests/unit/pages/exhibitions/exhibition/_chapter.spec.js
- packages/portal/tests/unit/pages/exhibitions/exhibition/index.spec.js
- packages/portal/tests/unit/pages/index.spec.js
- packages/portal/tests/unit/pages/stories/_.spec.js
- packages/portal/tests/unit/pages/themes/_.spec.js
- packages/portal/tests/unit/pages/themes/index.spec.js
* via pageMeta mixin
* to apply: w: 1200, h: 630, fit: 'fill', f: 'face'
> feat: standardise Contentful og:image params

- packages/portal/src/components/item/ItemMediaPresentation.vue
To avoid previous item data being shown while fetching.
> chore: render media viewer when fetch state is ready

- packages/portal/src/components/item/ItemMediaThumbnail.vue
because b-link/SmartLink with many many links is awful slow
> perf: use NuxtLink in ItemMediaThumbnail

- packages/portal/src/components/item/ItemMediaThumbnail.vue
- packages/portal/tests/unit/components/item/ItemMediaThumbnail.spec.js
use data instead, initialised in created
> perf: rm computed attrs from ItemMediaThumbnail

- packages/portal/src/components/item/ItemMediaThumbnail.vue
- packages/portal/tests/unit/components/item/ItemMediaThumbnail.spec.js
Reverts europeana/portal.js#2460
> Revert "perf: rm computed attrs from ItemMediaThumbnail"

- packages/portal/src/pages/item/_.vue
- packages/portal/tests/unit/pages/item/_.spec.js
to origins of:
* IIIF Presentation manifest
* first displayable web resource
> perf: item page head link preconnects

- packages/portal/src/components/item/ItemMediaThumbnails.vue
> fix: watch resources for thumbnails

- packages/portal/src/components/item/ItemMediaPresentation.vue
- packages/portal/tests/size/.size-limit.json
else thumbnail may be displayed when iiif is available
> fix: check for service on resource

- packages/portal/src/components/media/MediaAnnotationList.vue
- packages/portal/tests/unit/components/media/MediaAnnotationList.spec.js
it adds significantly to the size of the html as there may be many list items
> chore: rm annotation list item data-qa

- packages/portal/src/components/item/ItemMediaPresentation.vue
to prevent hydration errors on e.g. non-IIIF items w/ images
> fix: mv ItemMediaPresentation client-only higher

- packages/portal/src/mixins/klaro.js
- packages/portal/tests/unit/mixins/klaro.spec.js
if we are using our own component
> fix: don't render klaro

- packages/portal/src/components/embed/EmbedGateway.vue
- packages/portal/src/components/page/PageCookiesWidget.vue
- packages/portal/tests/unit/components/embed/EmbedGateway.spec.js
- packages/portal/tests/unit/components/page/PageCookiesWidget.spec.js
- tests/e2e/features/ZZ-finally/memory-usage.feature
to avoid race condition of trying to show it before it's rendered
> fix: show embed modal from within widget

- packages/portal/src/pages/item/_.vue
- packages/portal/tests/unit/pages/item/_.spec.js
showing the illustrated 404 error
> chore: add compatibility with tombstone records

- packages/portal/src/components/item/ItemLikeButton.vue
- packages/portal/src/store/set.js
- packages/portal/tests/unit/components/item/ItemLikeButton.spec.js
- packages/portal/tests/unit/store/set.spec.js
and call the plugin method directly
> refactor: rm set store createLikes

- packages/portal/src/components/recommendation/RecommendationButtons.vue
- packages/portal/src/components/set/SetAddItemModal.vue
- packages/portal/src/store/set.js
- packages/portal/tests/unit/components/recommendation/RecommendationButtons.spec.js
- packages/portal/tests/unit/components/set/SetAddItemModal.spec.js
- packages/portal/tests/unit/store/set.spec.js
and call the plugin method directly
> refactor: rm set store addItem

- packages/portal/src/components/item/ItemRemoveButton.vue
- packages/portal/src/components/set/SetAddItemModal.vue
- packages/portal/src/store/set.js
- packages/portal/tests/unit/components/item/ItemRemoveButton.spec.js
- packages/portal/tests/unit/components/set/SetAddItemModal.spec.js
- packages/portal/tests/unit/store/set.spec.js
and call the plugin method directly
> refactor: rm set store removeItem

- packages/portal/src/components/set/SetFormModal.vue
- packages/portal/src/store/set.js
- packages/portal/tests/unit/components/set/SetFormModal.spec.js
- packages/portal/tests/unit/store/set.spec.js
and call plugin method directly
> refactor: rm set store createSet

- packages/portal/src/plugins/europeana/set.js
- packages/portal/tests/unit/plugins/europeana/set.spec.js
- meta => minimal
- items => standard
- items.meta => itemDescriptions
> chore: adjust Set API get profile mappings

- packages/portal/src/pages/collections/_type/_.vue
- packages/portal/src/pages/exhibitions/_exhibition/_chapter.vue
- packages/portal/src/pages/galleries/_.vue
- packages/portal/src/pages/index.vue
- packages/portal/src/pages/search/index.vue
- packages/portal/src/pages/stories/_.vue
- packages/portal/src/pages/stories/index.vue
- packages/portal/tests/unit/pages/collections/_type/_.spec.js
- packages/portal/tests/unit/pages/collections/_type/index.spec.js
- packages/portal/tests/unit/pages/exhibitions/exhibition/_chapter.spec.js
- packages/portal/tests/unit/pages/exhibitions/exhibition/credits.spec.js
- packages/portal/tests/unit/pages/exhibitions/exhibition/index.spec.js
- packages/portal/tests/unit/pages/feature-ideas/index.spec.js
- packages/portal/tests/unit/pages/galleries/_.spec.js
- packages/portal/tests/unit/pages/galleries/index.spec.js
- packages/portal/tests/unit/pages/index.spec.js
- packages/portal/tests/unit/pages/item/_.spec.js
- packages/portal/tests/unit/pages/search/index.spec.js
- packages/portal/tests/unit/pages/stories/_.spec.js
- packages/portal/tests/unit/pages/stories/index.spec.js
- packages/portal/tests/unit/pages/themes/_.spec.js
for a slight improvement in test run time
> test: stub dynamic import components in pages

- packages/portal/src/components/item/ItemAddButton.vue
- packages/portal/src/components/item/ItemLikeButton.vue
- packages/portal/src/components/set/SetDeleteModal.vue
- packages/portal/src/components/set/SetFormModal.vue
- packages/portal/src/components/set/SetPublishButton.vue
- packages/portal/src/plugins/user-likes.client.js
- packages/portal/src/store/set.js
- packages/portal/tests/unit/components/item/ItemHero.spec.js
- packages/portal/tests/unit/components/item/ItemLikeButton.spec.js
- packages/portal/tests/unit/components/item/ItemPreviewCard.spec.js
- packages/portal/tests/unit/components/item/ItemPreviewCardGroup.spec.js
- packages/portal/tests/unit/components/set/SetDeleteModal.spec.js
- packages/portal/tests/unit/components/set/SetFormModal.spec.js
- packages/portal/tests/unit/components/set/SetPublishButton.spec.js
- packages/portal/tests/unit/plugins/user-likes.client.spec.js
- packages/portal/tests/unit/store/set.spec.js
- styleguide/styleguide.root.js
> refactor: reduce set store API interaction

- packages/portal/src/components/item/ItemPinModal.vue
by requesting item IDs separately
> chore: ItemPinModal show pinned on new Set API

- packages/portal/src/components/set/SetFormModal.vue
- packages/portal/tests/unit/components/set/SetFormModal.spec.js
until logic for differentiating w/ non-Gallery collections is introduced
> chore: disable collectionType "Gallery"

- packages/portal/src/plugins/europeana/set.js
to DRY up calls to get set numeric ID from URI
> refactor: add Set API plugin requestSet method

- packages/portal/src/store/set.js
on Set API v0.12 with profile=itemDescriptions and page param present
> fix: workaround for upstream empty set error

- README.md
- bin/update-node-version.js
- package-lock.json
- package.json
- packages/portal/Dockerfile
- packages/portal/tests/size/Dockerfile
- packages/portal/tests/size/package-lock.json
- packages/portal/tests/size/package.json
- styleguide/Dockerfile
Usage: `node ./bin/update-node-version.js 20`
> chore: create script to update node version

- packages/portal/src/components/item/ItemPreviewInterface.vue
- packages/portal/src/components/item/ItemSelectButton.vue
- packages/portal/src/components/item/ItemSelectToolbar.vue
- packages/portal/src/features/notifications.js
- packages/portal/src/features/toggles.js
- packages/portal/src/i18n/lang/en.js
It's live in production and the notification has expired.
> chore: rm itemMultiSelect feature toggle/notification

- packages/portal/src/pages/exhibitions/_exhibition/_chapter.vue
- packages/portal/src/pages/exhibitions/_exhibition/credits.vue
- packages/portal/src/pages/exhibitions/_exhibition/index.vue
- packages/portal/tests/unit/pages/exhibitions/exhibition/_chapter.spec.js
> refactor: rm final uses of Nuxt `asyncData`

- packages/portal/src/components/user/UserApiKeysTable.vue
- packages/portal/src/i18n/lang/en.js
- packages/portal/src/pages/account/api-keys.vue
- packages/portal/tests/unit/components/user/UserApiKeysTable.spec.js
- packages/portal/tests/unit/pages/account/api-keys.spec.js
- packages/style/scss/table.scss
- New component UserApiKeysTable to reuse for personal and project keys listing
- Adds Project API keys page section
> feat: project api keys table
