- plugins/europeana/search.js
- tests/unit/plugins/europeana/record.spec.js
- tests/unit/plugins/europeana/search.spec.js
`afterEach` hook added to plugin unit tests are to prevent a single failing test with unused nock stubs causing many others to appear to fail.
> Pagination of API searches

- tests/features/support/steps.js
Favour using the expect syntax which leads to the tests being consistent.
Assert seems to sometimes run outside of it's step and into the next scenario, meaning it causes flickering tests as it interferes with the loading of the next scenario.
> Use expect syntax

- tests/features/browse-page.feature
- tests/features/header.feature
- tests/features/record-page.feature
- tests/features/search/faceting.feature
- tests/features/search/pagination.feature
- tests/features/search/querying.feature
- tests/features/support/steps.js
* Await element presence before 'filling in' and click interactions, so that we don't need to explicitly test for these in the scenarios. (+removed all checks like this from scenarios)
* Visiting pages is a 'When' not a 'Given'
* Update language for the check that confirms presence of text in an element. (added 'the')
* Added a human readable getter for 'first page of results'
> Update e2e test syntax

- components/generic/InfoMessage.stories.js
- components/generic/InfoMessage.vue
- components/generic/PaginationNav.vue
- pages/search/index.vue
- plugins/europeana/search.js
- tests/features/search/pagination.feature
- tests/features/search/querying.feature
- tests/features/support/steps.js
- tests/unit/components/generic/InfoMessage.spec.js
- tests/unit/plugins/europeana/search.spec.js
* Add notice to last available page.*
* Set qfParams from url
* Hide notice/totals when there are no results/errors.
* Features and specs.
*The info notice for now has been added as its own component since it uses different data-qa and text decoration than the error notice. Perhaps these can be rolled into one component that takes more arguments(/configurations) along with the message notice. However for now that seems more complex than individual components.
Fixed a unit test warning by defaulting the pagination total results to be at least 1 as the bootstrap component expects a positive integer.
> Pagination refinements

- components/search/SearchFacet.vue
- pages/search/index.vue
- plugins/europeana/search.js
- plugins/vue-filters.js
- tests/features/search/faceting.feature
- tests/unit/components/search/SearchFacet.spec.js
- tests/unit/plugins/europeana/search.spec.js
* Support faceting by reusability with `reusability` URL parameter.
* Stop modifying the API's facets response and just pass to the templates as-is.
* Set the order in which facets should be displayed.
* DRY up the logic for generating new search routes
> Reusability pseudo facet

- README.md
- components/PageHeader.vue
- layouts/default.vue
- package.json
- pages/search/index.vue
- tests/features/search/querying.feature
- tests/features/support/step-definitions.js
- tests/features/support/step-runners.js
When leaving the search results page, remove the user's search query from the form input in the header, but ensure it is restored if they return using their browser's back button.
* Moves reading of the query up to the layout level which passes it down to the header component
* Uses a Vue "navigation guard" to observe when the search page is left for another, per https://router.vuejs.org/guide/advanced/navigation-guards.html#in-component-guards
* Uses an "event hub" to emit global events, per https://github.com/nuxt/nuxt.js/issues/849#issuecomment-307016399
> Watch for search query changes

- components/search/SearchResultsGrid.vue
- components/search/SearchResultsList.vue
- components/search/ViewToggles.vue
- pages/search/index.vue
- tests/features/search/view.feature
Use params and local/session storage to track views.
This PR also integrates all components and adds:
* Feature tests
* Styling for distinguishing active/inactive view toggles
* Stop emitting events when toggle doesn't change the value
> Persist search results `view` with params and storage

- components/generic/ContentCard.vue
- package-lock.json
- package.json
- tests/unit/components/generic/ContentCard.spec.js
As it results in malformed URLs SSR, due to Vue's escaping backslashes in dynamic style attributes.
> Stop CSS escaping background image URLs

- pages/search/index.vue
- tests/features/common/language-selector.feature
- tests/features/search/faceting.feature
- tests/features/search/querying.feature
- tests/features/support/step-runners.js
- When no query parameter is present in the url, redirect /search to /search?query=
> Search Redirect

- Jenkinsfile
To ensure binaries are rebuilt on node version updates
> Remove node_modules in build stage

- .env.example
- package-lock.json
- package.json
- server/index.js
Enabled by default on all environments.
To disable, set `DISABLE_REDIRECT_SSL=1` in your env.
> Redirect to SSL

- components/generic/CompareImageSlider.stories.js
- components/generic/CompareImageSlider.vue
- Created a wrapper which wraps around images and slider, while moving the figcaption element to the bottom of the component. This allows the handle to adjust accordingly when resizing the browser.
- Also fixed broken StoryBook issues
> fix compare image handle position

- .travis.yml
Let Ubuntu install the latest version it has available. Judging by the recent release timeline, by the time a new major version is released, the NPM package for chromedriver will have had an update too.
> Unversion chromium on Travis

- components/entity/EntityDetails.vue
- pages/entity/_type/_.vue
- plugins/europeana/entity.js
- plugins/europeana/utils.js
- store/entity.js
- tests/unit/components/entity/EntityDetails.spec.js
- tests/unit/plugins/europeana/entity.spec.js
On entity pages:
* Favour the title and description from Contentful
* If absent, use the values from the Entity API
* URL slugs also use the title from Contentful, but always in English
* This necessitates making an additional request to the Contentful Delivery API to get the English title, if the user is using a different language. Contentful does not offer a way to request multiple locales, it's either just one or all.
> Favour Contentful entity page title & description

- components/PageHeader.vue
As otherwise the placeholder is often occluded on the entity page with the pill present.
> Increase search box width

- .size-limit.json
- nuxt.config.js
Because it breaks local builds
> Remove Nuxt build filenames config

- components/generic/ContentCard.vue
- components/record/MetadataField.vue
- components/record/SimilarItems.stories.js
- components/record/SimilarItems.vue
- components/search/SearchResult.vue
- components/search/SearchResults.vue
- plugins/europeana/search.js
- plugins/europeana/utils.js
- tests/unit/components/generic/ContentCard.spec.js
- tests/unit/components/record/MetadataField.spec.js
- tests/unit/components/search/SearchInterface.spec.js
- tests/unit/components/search/SearchResult.spec.js
- tests/unit/components/search/SearchResults.spec.js
- tests/unit/plugins/europeana/search.spec.js
* Change structure of returned search results:
* Move all fields to top level of each object
* Return lang maps as-is instead of partially localising
* Add lang-aware dc:description
* Extend lang map l10n utility function to optionally omit URIs from values if other values are present
* Refactor search result and content card plugins to handle localised lang maps, outputting HTML lang attributes as necessary
* In content cards, permit each text to be a string, array of strings, or lang map, and normalise all to the format of localised lang map
> Localise search results

- components/browse/BrowseContentCard.vue
- components/search/SearchForm.vue
- pages/entity/_type/_.vue
- pages/record/_.vue
- plugins/europeana/api.js
- plugins/europeana/entity.js
- plugins/europeana/record.js
- plugins/europeana/search.js
- plugins/europeana/thumbnail.js
- store/collections/newspaper.js
- store/search.js
- tests/unit/plugins/europeana/entity.spec.js
- tests/unit/plugins/europeana/record.spec.js
- tests/unit/plugins/europeana/search.spec.js
- tests/unit/store/search.spec.js
Named `recordApi`, to:
* Permit future specification of other APIs by other params, e.g. `entityApi`
* Prevent conflict with existing parameter `api` used in Newspapers collection
In addition:
* Switch to using shorter API gateway URLs where possible, e.g. api.europeana.eu/record/ instead of api.europeana.eu/api/v2/
* Use plugins/europeana/api.js as the SSOT for API origins and path prefixes, including for data.europeana.eu
> Record API specification by URL param

- migrations/0019-update-reserved-slugs.js
- Updated reserved slugs on browse pages
- Updated help texts for slug field on gallery and exhibition pages
> Contentful migration: update help texts + validation

- components/generic/ContentCard.vue
- components/record/MetadataField.vue
- components/search/SearchResults.vue
- plugins/europeana/utils.js
- tests/unit/components/record/MetadataField.spec.js
Always prefer Text values which aren't URIs for metadata display. Even if they are only available in non preferred languages.
Introduce a new option to be used on search results to omit any URIs when they're the only info to display. As this is configurable, record pages will still output these URIs.
> Extra lookups for metadata URI values

- assets/scss/cards.scss
gaps/height issues on safari were caused by:
```
.masonry { display: inline-block; }
.content-card { transform: translateZ(0) }
```
I can't see any reason for using inline-block over block and this removes the huge gap below the cards. transform: translateZ(0) was causing the gaps between the cards, again can't see any reason for this styling.
> fixed safari masonry bug

- .size-limit.json
- components/browse/BrowseSections.vue
- components/search/SearchInterface.vue
- layouts/default.vue
- package.json
- pages/blog/_.vue
- pages/blog/index.vue
- pages/collections/_type/_.vue
- pages/exhibitions/_exhibition/_chapter.vue
- pages/exhibitions/_exhibition/index.vue
- pages/galleries/_.vue
- pages/galleries/index.vue
- pages/item/_.vue
This work seeks to improve performance, of SSRs in particular, by:
1. Moving the rendering of certain components to client-side only, where deemed auxilliary content
2. Having the footer render client-side brings a significant improvement to every page
3. Introducing code-splitting for some components where their use is conditional
> Client-side rendering

- .env.example
- components/PageHeader.vue
- components/search/AutoSuggest.vue
- components/search/SearchForm.vue
- layouts/default.vue
- plugins/europeana/entity.js
- tests/unit/components/search/AutoSuggest.spec.js
In addition:
* Remove the unused & experimental entity suggestion validation against record existence
* Stop passing lang maps to the auto-suggest as only ever one will now be present; instead just pass the matching string literal
> Also use entity altLabel for suggestion matches

- components/search/SearchInterface.vue
- tests/unit/components/search/SearchInterface.spec.js
Notes:
* The session storage value has been changed from a boolean to a string in order to better reflect the fact that in real browsers, stored values are always typecast to strings
> Watch for changes to contentTier to show toast

- components/search/AutoSuggest.vue
- components/search/SearchForm.vue
solution based on this thread https://forum.vuejs.org/t/blur-before-click-only-on-safari/21598/7?u=suth_a
> Fix safari blur bug

- components/search/SearchInterface.vue
This would be a temporary fix for initial load and detection of the 'view' param.
There are issues/inconsistencies with preservation of the param when navigating after the initial load.
> Fix for initial list view detection

- components/item/MetadataBox.stories.js
- components/item/MetadataBox.vue
- pages/item/_.vue
Refactor the metadatabox into it's own component in order to use it in storybook and demonstrate how it expands to the width of it's container.
> Metadata box refactor

- components/generic/ContentCard.vue
- components/generic/OptimisedImage.vue
- tests/features/support/step-runners.js
And pause after moving to pagination container before clicking on links, in e2e tests.
> Restore lazy-loading on test env

- .github/workflows/ci.yml
- .github/workflows/recycling.yml
- .github/workflows/support/ci/.env
- .github/workflows/support/ci/manifest.yml
- .github/workflows/support/ci/slack-notification.json
Introduces two [GitHub Actions workflows](https://docs.github.com/en/actions):
1. [CI](https://github.com/europeana/portal.js/actions?query=workflow%3ACI), triggered when pull requests are opened, synchronized (i.e. updated with more commits to the branch), or reopened:
1. generates a .env file to use for the app from a template and [GitHub secrets](https://github.com/europeana/portal.js/settings/secrets) (plus some hard-coded values that are not secrets)
1. checks out the code for the PR
1. installs the Node packages and builds the Nuxt app
1. pushes the app to IBM Cloud Foundry
1. if this is the first push of this app to Cloud Foundry, sends a notification to a Slack channel
2. [Recycling](https://github.com/europeana/portal.js/actions?query=workflow%3ARecycling), triggered when pull …
> GitHub workflow to deploy PRs to CF

- .env.example
- .github/workflows/support/ci/.env
- nuxt.config.js
- package-lock.json
- package.json
- pages/item/_.vue
- static/robots.txt
- tests/unit/pages/item/_.spec.js
Also introduces unit tests for Nuxt page views. We have in the past relied on e2e tests for these, but not everything is readily testable thus, and they contain plenty of logic that should be unit tested. While Vue Test Utils may not be aware of some of the Nuxt methods, it's straightforward enough to supply them onto the local Vue wrapper's VM once created.
> Restore og:image for item page

- components/generic/RelatedChip.vue
- tests/unit/components/generic/RelatedChip.spec.js
To test this locally:
* Enable SSL negotiation with `ENABLE_SSL_NEGOTIATION=1`
* Ensure the SSL blacklist includes dataset 08711, e.g. with `SSL_DATASET_BLACKLIST=08711`
* Open http://localhost:3000/en/item/08711/item_150452, and observe that the "COLLECTIONS YOU MIGHT LIKE" link to Geology points correctly to https://localhost/en/collections/topic/152-geology (which may or may not then work, depending on whether you have SSL set up)
> Detect linkTo having scheme, and use href, not to

- components/generic/RelatedChip.vue
- components/generic/SmartLink.vue
- components/search/SearchQueryOptions.vue
- nuxt.config.js
- plugins/link.js
- tests/unit/components/generic/RelatedChip.spec.js
- tests/unit/components/generic/RelatedCollections.spec.js
- tests/unit/components/search/SearchQueryOptions.spec.js
- tests/unit/plugins/link.spec.js
Introduces a link plugin, and injects it onto the Nuxt context / Vue instance as `$link`, with two methods:
* `$link.to(path, query = {})`: returns null if the path is an absolute URL, i.e. contains "://", otherwise returns an object with path and query properties for routing with
* `$link.href(path, query = {})`: returns a URL including the query if the path is an absolute URL, otherwise null
These can be used in tandem on component props where only one or the other is wanted, owing to only one ever having a non-null return value, e.g.
```vue
<b-link
:to="$link.to(path)"
:href="$link.href(path)"
/>
```
> Link plugin to detect when to use href, when to use router to

- nuxt.config.js
Leave it to a gateway/reverse proxy like NGINX or Cloudflare.
**Benchmarks**
Setup: 
* API proxy cache deployed to Cloud Foundry with 1 day retention in memory, /en warmed up
* Portal deployed to Cloud Foundry, with NGINX gateway in front of it, and Cloudflare proxying enabled at FQDN www-test.europeana.eu
* Benchmark command: `ab -k -n 100 -c 10 -H "Accept-Encoding: gzip" "https://www-test.europeana.eu/en"`
Results:
* With compressor enabled on Nuxt:
`Time per request:       395.785 [ms] (mean, across all concurrent requests)`
* With compressor disabled on Nuxt, responses are still gzipped, by Cloudflare:
`Time per request:       307.560 [ms] (mean, across all concurrent requests)`
> Disable compressor

- src/modules/contentful-graphql/queries/link-groups.graphql
don't check unused linkGroups boolean in footer links
> Update footer graphQL

- src/lang/en.js
- src/plugins/klaro-config.js
https://blog.cloudflare.com/deprecating-cfduid-cookie/
> Remove Cloudflare from Klaro services

- src/components/PageHeader.vue
- src/components/PageNavigation.vue
- tests/unit/components/PageNavigation.spec.js
Refactored:
1. Move declaration of navigation links from PageHeader into PageNavigation, the only place they are used
2. Reuse the main navigation links in the sidebar navigation instead of declaring them twice
3. Rename the `name` property of the auth links to `url` for consistency with main and sidebar links
4. Where possible, derive the icon for sidebar navigation links from the final component of the URL, e.g. `/collections` derived as `icon-collections`, `/account/logout` derived as `icon-logout`, but `/about-us` is an explicit exception as `icon-info`
5. Make the PageNavigation unit test do something, as it was not testing anything at all previously
> DRY SSOT for navigation links

- Dockerfile
To prevent changes to version number without changes to dependencies resulting in rerunning `npm install` on Docker image builds.
> chore: ignore version number in package lock on install

- src/plugins/europeana/search.js
- src/plugins/europeana/utils.js
- tests/unit/plugins/europeana/search.spec.js
Reductions:
* Pick fields we need for search result display
* Reduce lang maps to values needed for user's locale
* Truncate lang map values
> perf: reduce and freeze search response items

- src/plugins/europeana/auth.js
- src/plugins/europeana/set.js
- tests/unit/plugins/europeana/auth.spec.js
- tests/unit/plugins/europeana/set.spec.js
To handle the situation where a request with authorization fails because the tokens are invalid, but the request may not need authorization anyway, e.g. when viewing a public set. Removes the tokens and retries the request. If it does not require authorization, it will then succeed; if it does require authorization, then it will receive the relevant error message.
Also addresses an issue with difference in behaviour between dev/production builds when requesting a public set without any authorization, where dev builds were redirecting to login instead of displaying the set.
> Retry request without auth when token refresh request fails

- src/components/account/UserSets.vue
- src/components/set/AddItemToSetButton.vue
- src/components/set/AddItemToSetModal.vue
- src/store/set.js
- tests/unit/components/account/UserSets.spec.js
- tests/unit/components/set/AddItemToSetButton.spec.js
- tests/unit/components/set/AddItemToSetModal.spec.js
- tests/unit/store/set.spec.js
Then fetch edm:previews for sets from Record API with minimal profile, and store in a new state property.
Why? Because the itemDescriptions profile becomes very slow as the user's number of sets and/or the number of items in sets increases, greatly impairing the UX of the add to gallery feature, and the only reason we request it is to get an edm:preview for the sets from one of the items in that set.
These changes greatly improve the time-to-interaction of the modal for adding items to galleries, e.g. from ~ 1 second to ~ 125 ms with 8 sets, some being empty and only one having 40-50 items.
However... one drawback of this approach is that the preview for a set will only ever consider the first item in the set, i.e. it won't go looking over all items in the set until it finds an …
> Fetch creations with standard profile

- nuxt.config.js
- src/components/generic/AlertMessage.vue
- src/components/generic/ContentCard.vue
- src/components/generic/InfoMessage.vue
- src/components/generic/PaginationNav.vue
- src/components/item/MetadataBox.vue
- src/components/item/SummaryInfo.vue
- src/components/search/ViewToggles.vue
- src/layouts/default.vue
- src/mixins/stripMarkdown.js
- src/pages/account/index.vue
- src/pages/collections/organisations.vue
- src/pages/galleries/_.vue
- src/plugins/vue-filters.js
- tests/size/.size-limit.json
- tests/size/package.json
- tests/unit/mixins/stripMarkdown.spec.js
- tests/unit/plugins/vue-filters.spec.js
Optimisations to Nuxt config:
1. Enable building source maps in webpack to facilitate debugging in production builds, for instance identifying the source line at which errors occurred, or showing the source module responsible for unused JS identified by Lighthouse performance reports.
2. ~~Enable extractCSS to prevent inlining CSS in HTML, reducing the size of the initial document transfer (by 57 kB/45% on the homepage), but increasing the number of network requests required. Lighthouse performance reports favour extracted CSS.~~ Disabled as it messes up some CSS. See: https://github.com/nuxt/nuxt.js/issues/4219
3. Enable "modern" builds to have Nuxt generate an additional client-side bundle using ECMAscript which will be served to modern browsers detected as supporting it. The modern …
> chore: optimize Nuxt build config and Bootstrap Vue plugin registration

- src/components/item/MetadataBox.vue
- src/pages/item/_.vue
- src/plugins/europeana/record.js
- tests/unit/components/item/MetadataBox.spec.js
**What?**
In the record plugin's parsing of Record API responses, stop differentiating and separating fields as core & extra. Instead, return all together as a single metadata object. Then, make the distinction only where it is needed, i.e. in the MetadataBox component.
**Why?**
* Separation of concerns: intermediate views such as the item page should not need to know whether title, description, etc will be in core or extra fields as that distinction is only relevant in the metadata box.
* Moves the field names for core and extra into the metadata box component where it is easier to locate and modify them (as it is the only component doing so would affect).
* Reduction in duplication of logic for entity lookups in the record plugin as it's only done once.
* Reduction in size of the record …
> refactor: return single metadata fields object from record plugin

- nuxt.config.js
- src/modules/elastic-apm/index.js
- src/modules/elastic-apm/plugin.server.js
- src/server-middleware/api/index.js
We recently enabled `usePathAsTransactionName` in the Elastic APM config (in nuxt.config.js) to alleviate all SSR transactions being recorded as "unknown route". This results in the full URL being recorded instead, which is better than nothing, but better would be for those to be grouped by the underlying route handler, i.e. the Nuxt page.
This PR achieves that by:
* Add a server-side plugin to the elastic-apm module to set the APM transaction name for Nuxt SSRs based on the current Vue route, reusing the logic from `@elastic/apm-rum-vue`
* Tweak API server middleware Express app to include `/_api/` prefix in transaction names
* Adjust Elastic APM agent config to not set transaction name by full URL (so any unmatched will again be registered as "unknown route"), and to ignore any …
> chore: group Elastic APM transactions by Vue route

- nuxt.config.js
- package-lock.json
- package.json
- src/modules/contentful-graphql/plugin.js
- src/plugins/europeana/annotation.js
- src/plugins/europeana/entity-management.js
- src/plugins/europeana/entity.js
- src/plugins/europeana/record.js
- src/plugins/europeana/search.js
- src/plugins/europeana/set.js
- src/plugins/europeana/utils.js
- tests/unit/plugins/europeana/search.spec.js
* Start capturing errors from various API requests to Elastic APM
* Use [axios-retry](https://www.npmjs.com/package/axios-retry) to retry failed Contentful GraphQL requests (3 times by default)
* Instruct Elastic APM to ignore Kubernetes health check user agent
> chore: capture errors to APM & retry CTF requests

- .env.example
- .github/workflows/docker-images.yml
- .github/workflows/support/docker-images/.npmrc
- .github/workflows/support/docker-images/warm-up-jsdelivr.sh
- nuxt.config.js
* After building versioned Docker images, publish the app package to NPM
* After publishing the app package to NPM, warm up the jsdelivr.net cache for client bundle files for that version
* Add a feature toggle to support loading all client bundle files from jsdelivr.net instead of having Nuxt serve them
Example of a successful Actions run: https://github.com/europeana/portal.js/actions/runs/1421046089
Resulting in NPM package: https://www.npmjs.com/package/@europeana/portal/v/1.53.1-npm-publish.12
And jsdelivr.net CDN: https://cdn.jsdelivr.net/npm/@europeana/portal@1.53.1-npm-publish.12/
> chore: publish to NPM & warm up jsdelivr.net CDN

- src/modules/contentful-graphql/queries/blog-post-page.graphql
- src/modules/contentful-graphql/queries/exhibition-chapter-page.graphql
- src/modules/contentful-graphql/queries/exhibition-landing-page.graphql
- src/pages/exhibitions/_exhibition/_chapter.vue
Also adds assignment in the asyncdata for exhibition chapters. 
The same has not been done on the blog and exhibition landing pages as there the whole graphql response is already available to the template.
Example:
`contentWarning.name` & `contentWarning.description` for exhibition landing pages.
or
`post.contentWarning.name` & `post.contentWarning.description` for blogs.
> Graphql for exhibition & blog content warnings

- src/components/generic/ContentCard.vue
- tests/unit/components/generic/ContentCard.spec.js
The fix is the change to move each part of the hit highlight templating (p and strong tags; prefix, suffix and exact texts) onto its own line. The other changes are just to remove some superfluous uses of the Vue template element.
> fix: prevent hydration error on hit highlights

- src/components/generic/PaginationNav.vue
- src/components/search/SearchInterface.vue
- src/components/search/SideFacetDropdown.vue
- src/components/search/SideFilters.vue
- src/pages/blog/index.vue
- src/pages/collections/_type/_.vue
- src/pages/collections/persons.vue
- src/pages/exhibitions/index.vue
- src/pages/galleries/index.vue
- src/pages/search/index.vue
- src/store/entity.js
- src/store/search.js
- tests/e2e/features/search/querying.feature
- tests/unit/components/search/SearchInterface.spec.js
- tests/unit/components/search/SideFacetDropdown.spec.js
- tests/unit/components/search/SideFilters.spec.js
- tests/unit/pages/collections/type/_.spec.js
- tests/unit/store/search.spec.js
- tests/unit/utils.js
When side filters are enabled for search, only retrieve facets one-at-a-time and when they are needed, i.e. when the user shows that facet's dropdown, and unless they have previously been retrieved and would not have changed since.
Also:
* Fix the side filters on the search within a collection, which were instead running a full site search
* The contentTier filter must always be fetched (client-side) because it's needed for displaying the toast
* Move the responsibility for triggering the Record API search and facet requests from page views into the search interface component
* Make the search interface component use the newer-style Nuxt `fetch` with the loading indicator
* Remove use of `v-model` from PaginationNav.vue component, leaving Bootstrap Vue's Pagination Nav to deduce the page …
> refactor: request single facets when needed

- src/components/search/SideFacetDropdown.vue
- src/components/search/SideFilters.vue
- tests/unit/components/search/SideFacetDropdown.spec.js
* Keep the facet API requests isolated to a single facet at a time...
* ...but don't wait for user interaction, i.e. request them all in advance, in multiple API requests
* Only render the filter dropdowns client-side, to get a speedy initial server response time
* Once a facet API response is received, if a facet has no available fields, remove it from display
* When URL query parameters change that may affect the facets, immediately re-request all of them
> refactor: request individual facets up front

- .env.example
- nuxt.config.js
- src/plugins/europeana/search.js
- tests/unit/plugins/europeana/search.spec.js
Enabled by env var:
```
APP_SEARCH_TRANSLATE_LOCALES=es
```
> feat: add config setting for locales to translate search

- .github/workflows/ci.yml
- .github/workflows/support/docker-images/warm-up-jsdelivr.sh
- Dockerfile
[distroless images](https://github.com/GoogleContainerTools/distroless) are smaller and more secure.
For portal.js, the final image is reduced from 267 MB to 250 MB.
Also:
* switch to using `npm ci` in the Dockerfile, which is faster
* reduce the number of stages
> chore: use distroless base image

- Dockerfile
- bin/pkg-versions.js
- bin/sonar-project-version.js
- nuxt.config.js
- package-lock.json
- package.json
- pkg-versions.js
- src/layouts/contentful.vue
- src/layouts/default.vue
- src/server-middleware/api/version.js
- tests/e2e/features/ZZ-finally/memory-usage.feature
Instead, create a file ./pkg-versions.js with hard-coded values for the package versions of the app itself, @nuxt/core, bootstrap and bootstrap-vue.
The version numbers in this file can be automatically updated using the new script `node bin/pkg-versions.js`.
> chore: stop using experimental JSON imports

- bin/sonar-project-version.js
- src/server-middleware/api/version.js
As npm is not present in the distroless image.
> chore: read version from pkg-versions.js

- src/components/search/SideFacetDropdown.vue
- src/store/search.js
map state for facet options, otherwise they're undefined.
> bug: fix newspaper fulltext facets

- src/components/entity/EntityRelatedCollections.vue
- src/pages/collections/_type/_.vue
- src/plugins/europeana/entity.js
- src/plugins/europeana/record.js
- tests/unit/components/entity/EntityRelatedCollections.spec.js
- tests/unit/plugins/europeana/record.spec.js
Primarily to reduce the amount of logic in the collections page .vue, and move code from entity and record plugins only used for this component into the component.
Also:
* Fix favouring editorially linked collections coming from Contentful, e.g. for the Fashion theme
Re EC-5767
> refactor: create EntityRelatedCollections component

- .env.example
- src/assets/scss/cards.scss
- src/components/related/RelatedEditorial.vue
- src/features/toggles.js
- src/modules/contentful-graphql/queries/related-content.graphql
- src/pages/collections/_type/_.vue
- src/pages/search/index.vue
- tests/unit/components/related/RelatedEditorial.spec.js
1. Search for related editorial content in Contentful from the main search, provided the user has entered a query
1. NB: this requires a separate GraphQL query because without an entity URI supplied, the other query will never return anything due to the use of the `_contains_some` filter
2. Fix the related editorial content search for collection pages to filter blog posts by the query if there is one
3. Remove the feature toggle as this is the final part of the initial implementation of the display of related editorial
> feat: search editorial content from main search

- src/components/PageHeader.vue
- src/components/search/SearchForm.vue
- src/components/search/SearchQueryOptions.vue
- styleguide.config.cjs
- styleguide/styleguide.root.js
- tests/e2e/docker/nightwatch/support/step-runners.js
- tests/unit/components/PageHeader.spec.js
- tests/unit/components/search/SearchForm.spec.js
- tests/unit/components/search/SearchQueryOptions.spec.js
Refactor to improve and clean up the search form and related components. This includes:
- Move back button from PageHeader to SearchForm component
- Move clear and filter buttons outside b-form. The HTML form should only include the search input
- Logic to close the search options dropdown when clicking outside the SearchForm (or its children, i.e. SearchQueryOptions)
- logic to handle keyboard navigation with arrow keys to select a search option
- Clean up deprecated logic for tracking matomo event on search option selection with enter key. This now happens outside the form element and is tracked on click anyway
- Clean up deprecated logic for manually setting focus on search options
- Add PageHeader and SearchQueryOptions components to the style guide
> refactor: SearchForm, SearchQueryOptions and PageHeader components

- src/components/blog/BlogPost.vue
- src/components/entity/EntityRelatedCollections.vue
- src/components/related/RelatedCollections.vue
- src/components/search/RelatedSection.vue
- src/modules/contentful-graphql/queries/exhibition-chapter-page.graphql
- src/modules/contentful-graphql/queries/exhibition-credits-page.graphql
- src/modules/contentful-graphql/queries/exhibition-landing-page.graphql
- src/pages/blog/_.vue
- src/pages/exhibitions/_exhibition/_chapter.vue
- src/pages/exhibitions/_exhibition/credits.vue
- src/pages/exhibitions/_exhibition/index.vue
- src/pages/item/_.vue
- tests/size/.size-limit.json
- tests/unit/components/entity/EntityRelatedCollections.spec.js
- tests/unit/components/related/RelatedCollections.spec.js
* Move RelatedCollections component to src/components/related/ directory
* Add a new prop, `entityUris`, to RelatedCollections component. If present and `relatedCollections` is not populated, go fetch the data for those entities to render in the component
* Refactor EntityRelatedCollections component to make use of the new prop of RelatedCollections
* Add use of RelatedCollections to blog post and exhibitions landing pages
> feat: link to related entities from blogs and exhibitions

- src/features/toggles.js
- src/pages/stories/index.vue
- tests/unit/pages/stories/index.spec.js
i.e. remove feature toggle, so it's always enabled
> chore: stories page launch clean up

- src/components/related/RelatedCategoryTags.vue
- src/pages/stories/index.vue
- tests/unit/components/related/RelatedCategoryTags.spec.js
- tests/unit/pages/stories/index.spec.js
Fixes for:
1. Deleting a category content entry prevents the /stories page from loading if blog posts or exhibitions are linked to that category
2. Deleting a category content entry prevents any individual blog post or exhibition page from loading it if the respective entry linked to it
3. Archiving or deleting the stories browse page in CTF prevents the /stories page from loading
> fix: handle absent linked entries

- packages/portal/src/components/search/SideFacetDropdown.vue
Status messages are read out by screen-readers on content changes so visually impaired users are noted of these changes on the page. When **adding** a filter option it reads out "[option name] removed". In this case the status messages are created by Bootstrap-Vue's form-tags component.
This PR fixes the status message by passing the selected option and not just the label. Then Bootstrap-Vue can compare the tags/options properly and create the correct status messages.
> fix: status messages for adding filter options

- packages/portal/src/components/entity/EntityRelatedCollections.vue
- packages/portal/src/components/item/ItemPreviewCardGroup.vue
- packages/portal/src/components/related/RelatedCollections.vue
- packages/portal/src/components/search/RelatedSection.vue
- packages/portal/src/components/search/SearchInterface.vue
- packages/portal/src/pages/collections/_type/_.vue
- packages/portal/src/pages/search/index.vue
- packages/portal/tests/unit/components/entity/EntityRelatedCollections.spec.js
- packages/portal/tests/unit/components/related/RelatedCollections.spec.js
- packages/portal/tests/unit/components/search/RelatedSection.spec.js
- packages/portal/tests/unit/components/search/SearchInterface.spec.js
- packages/portal/tests/unit/pages/collections/_type/_.spec.js
- packages/portal/tests/unit/pages/search/index.spec.js
To prevent repeating API requests.
* Make search/RelatedSection and entity/EntityRelatedCollections components emit the data they retrieve for related collections, and have the parent view store it then pass it back to those components as a prop, so that if those components need to be re-rendered, the data does not need to be re-fetched from APIs
* Refactor (and simplify) the logic for showing/hiding those components in the `related` slot of the item/ItemPreviewCardGroup component, to make the Masonry display more stable
> fix: store related collections

- .github/workflows/ci.yml
- .github/workflows/recycling.yml
- .github/workflows/styleguide.yml
Re https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> chore: update actions for Node 12 deprecation

- packages/portal/src/components/item/ItemHero.vue
- packages/portal/src/pages/account/index.vue
- packages/portal/src/pages/collections/_type/_.vue
- packages/portal/src/pages/galleries/_.vue
- packages/portal/src/pages/set/_.vue
- packages/portal/src/plugins/authScheme.js
- packages/portal/src/plugins/oauth2.js
- packages/portal/tests/unit/components/item/ItemHero.spec.js
- packages/portal/tests/unit/pages/account/index.spec.js
- packages/portal/tests/unit/pages/collections/_type/_.spec.js
- packages/portal/tests/unit/pages/galleries/_set.spec.js
- packages/portal/tests/unit/pages/set/_.spec.js
- packages/portal/tests/unit/plugins/authScheme.spec.js
* Via the custom `RuntimeConfigurableOauth2Scheme` auth scheme class in `packages/portal/src/plugins/authScheme.js`, decorate `$auth` in the Nuxt context with a helper function, `userHasClientRole` which checks whether the logged-in user has a specific Keycloak/oAuth2 client role.
* For example, to check if the logged-in user has the editor role of the entities client: 
```js
this.$auth.userHasClientRole('entities', 'editor')
```
* Update code to use this new helper function
* Add a dummy `Oauth2Scheme` class in `packages/portal/src/plugins/oauth2.js`, purely to facilitate testing `authScheme.js`, which when Nuxt is built, will still extend the auth module's `Oauth2Scheme` class
* Add unit tests for `authScheme.js` to get coverage to 100%
> refactor: add userHasClientRole helper to $auth

- packages/portal/src/assets/scss/cards.scss
- packages/portal/src/components/blog/BlogPost.vue
- packages/portal/src/components/related/RelatedCategoryTags.vue
- packages/portal/src/components/related/RelatedCollections.vue
- packages/portal/src/components/search/QuickSearch.vue
- packages/portal/src/components/search/RelatedSection.vue
- packages/portal/src/pages/collections/_type/_.vue
- packages/portal/src/pages/exhibitions/_exhibition/_chapter.vue
- packages/portal/src/pages/exhibitions/_exhibition/credits.vue
- packages/portal/src/pages/exhibitions/_exhibition/index.vue
- packages/portal/src/pages/item/_.vue
- packages/portal/tests/unit/components/related/RelatedCollections.spec.js
- Sets default 0.5rem margins for badges
- Overrides to 0.75rem margins for badges inside related cards
- Aligns related-heading margins when used for badges/tags
> refactor: align related badge pill spacing

- packages/portal/src/components/account/CreateSetButton.vue
- packages/portal/src/components/account/UserSets.vue
- packages/portal/src/components/generic/PaginationNavInput.vue
- packages/portal/src/components/set/AddItemToSetModal.vue
- packages/portal/src/lang/en.js
- packages/portal/src/pages/account/index.vue
- packages/portal/src/plugins/europeana/annotation.js
- packages/portal/src/plugins/europeana/search.js
- packages/portal/src/plugins/europeana/utils.js
- packages/portal/src/store/set.js
- packages/portal/tests/size/.size-limit.json
- packages/portal/tests/unit/components/account/UserSets.spec.js
- packages/portal/tests/unit/components/set/AddItemToSetModal.spec.js
- packages/portal/tests/unit/pages/account/index.spec.js
- packages/portal/tests/unit/plugins/europeana/search.spec.js
- packages/portal/tests/unit/store/set.spec.js
* Introduce pagination in the galleries tabs of the my account page (UserSets component). 20 items at a time unless the create set button is shown, in which case 19 items at a time.
* Add a new tab for published galleries to the my account page
* Stop using the store for retrieval of the logged-in user's sets, and do so in the respective components instead
* Only load the sets when needed for the tab displayed, not all of them in advance
* Update the PaginationNav component to also preserve the hash from the route
* Update API plugins and utils so that the axios params serializer always repeats for arrays, e.g. `qf`
> feat: add pagination to user sets in account

- packages/portal/src/components/item/ItemRecommendations.vue
- packages/portal/src/store/set.js
- packages/portal/tests/unit/components/item/ItemRecommendations.spec.js
- packages/portal/tests/unit/store/set.spec.js
On the item page:
* omit any self-recommendations (bug in Recommendation API/Engine)
* limit to 8
On the set page:
* omit any recommendations for items already in the set (bug in Recommendation API/Engine)
* show whatever remains
> feat: prune recommended items

- packages/portal/nuxt.config.js
- packages/portal/src/modules/axios-logger/templates/plugin.js
- packages/portal/tests/unit/modules/axios-logger/templates/plugin.spec.js
To be used in scenarios such as SSRs to a Kubernetes deployment where the API is on the same cluster, avoiding the use of external networking/DNS.
e.g. `EUROPEANA_RECORD_API_URL_PRIVATE: http://search-api-service-test.test.svc.cluster.local/record`, if service name is "search-api-service-test", namespace is "test" and port is exposed to network as 80.
> feat: optional internal/private API URLs

- tests/e2e/docker/docker-compose.yml
Running the e2e tests via Docker Compose hangs for 30s after starting the containers, due to the [default healthcheck interval](https://docs.docker.com/engine/reference/builder/#healthcheck) (for the Chrome containers) being 30s.
This reduces that interval to 5s, so e2e tests will start running 25s earlier, provided the healthcheck passes.
> chore: reduce interval and timeout on chrome healthcheck

- .github/workflows/ci.yml
* sets a size limit on the built Docker image for the portal app (280M)
* tests this during the GHA CI workflow
* if OK, outputs a notice annotation (shown on the [GHA summary](https://github.com/europeana/portal.js/actions/runs/4353326438))
* if too big, output an error annotation (shown on the [GHA summary](https://github.com/europeana/portal.js/actions/runs/4353356150))
> chore: test size of docker image

- packages/portal/src/components/search/SideFilters.vue
- packages/portal/tests/unit/components/search/SideFilters.spec.js
properly remove the api filter on theme exit/switch.
fix the resettable count for the api filter as it will be reset to the standard default, not the theme's default
> fix: api filter - sidebar fixes

- packages/portal/src/components/metadata/MetadataBox.vue
- packages/portal/src/lang/en.js
- packages/portal/src/pages/item/_.vue
- packages/portal/tests/unit/pages/item/_.spec.js
Changes:
* remove transcription tab from item page, and remove redundant UI text for that tab
* filter annotations retrieved on item page to those with motivation `linkForContributing` or `tagging`
* add a computed property on item page for data provider entity prefLabel
* add handling to the entity retrieval on the item page to prevent making an Entity API request should there be no related entities
> feat: filter item page annotation motivations

- packages/portal/.env.example
- packages/portal/nuxt.config.js
- packages/portal/src/cachers/README.md
- packages/portal/src/cachers/collections/index.js
- packages/portal/src/cachers/collections/organisations/count.js
- packages/portal/src/cachers/index.js
- packages/portal/src/cachers/matomo/visits.js
- packages/portal/tests/unit/cachers/collections/index.spec.js
- packages/portal/tests/unit/cachers/collections/organisations/count.spec.js
- packages/portal/tests/unit/cachers/matomo/visits.spec.js
* Matomo REST API auth token needs to be set in env var `MATOMO_AUTH_TOKEN`
* New cachers:
* `collections:organisations:count` - caches the number of Europeana-scoped organization-type entities
* `matomo:visits` - caches the number of Matomo visits yesterday to the configured site
* NOTE: no new cacher for the total number of items, as that can be derived from the total of all the type-specific items already cached in `items:type-counts`
> feat: cache Matomo visits and organization count

- packages/portal/.env.example
- packages/portal/nuxt.config.js
- packages/portal/src/components/search/SearchInterface.vue
- packages/portal/src/pages/collections/_type/_.vue
- packages/portal/src/plugins/europeana/search.js
- packages/portal/tests/unit/components/search/SearchInterface.spec.js
- packages/portal/tests/unit/pages/collections/_type/_.spec.js
- packages/portal/tests/unit/plugins/europeana/search.spec.js
* Two new env vars:
* `APP_SEARCH_COLLECTIONS_CLIENT_ONLY`: Search for related items on the collections pages client-side only. If not enabled, items will be searched for server-side too.
* `APP_SEARCH_COLLECTIONS_DO_NOT_TRANSLATE`: Prevent translation of search results, i.e. related items, on the collections pages, even for the locales set in `APP_SEARCH_TRANSLATE_LOCALES.`
* SearchInterface has a new prop, `doNotTranslate`, which will prevent search translation from running even in the configured locales, and which CollectionPage will pass in based on `APP_SEARCH_COLLECTIONS_DO_NOT_TRANSLATE` env var
* In search plugin, stop looking at app config for translation, and instead just look at supplied options, for `translateLang` param, which SearchInterface now supplies
* Fix bug where …
> chore: client-only SearchInterface on collection page

- packages/portal/src/components/authored/AuthoredHead.vue
- packages/portal/src/components/browse/BrowseSections.vue
- packages/portal/src/components/generic/StackedCardsSwiper.vue
- packages/portal/src/components/image/ImageOptimised.vue
- packages/portal/src/components/image/ImageWithAttribution.vue
- packages/portal/src/components/image/ImageWithAttributionContainer.vue
- packages/portal/src/components/landing/LandingImageCard.vue
- packages/portal/src/components/landing/LandingImageCardGroup.vue
- packages/portal/src/components/landing/LandingInfoCard.vue
- packages/portal/src/components/landing/LandingInfoCardGroup.vue
- packages/portal/src/components/landing/LandingPage.vue
- packages/portal/tests/size/.size-limit.json
- packages/portal/tests/unit/components/landing/LandingImageCard.spec.js
- packages/portal/tests/unit/components/landing/LandingImageCardGroup.spec.js
- packages/styleguide/styleguide.root.js
- Split `ImageWithAttribution` component into a container and sub component to reuse without the container + jumbotron wrappers
- Add `srcset` and `sizes` attributes to `ImageOptimised` to pass in responsive images
- Add new `LandingImageCard `and `LandingImageCardGroup` components
> feat: landing page image card group

- packages/portal/src/components/browse/BrowseAutomatedCardGroup.vue
- packages/portal/src/components/entity/EntityTable.vue
- packages/portal/src/server-middleware/api/cache/index.js
- packages/portal/src/server-middleware/api/index.js
- packages/portal/tests/unit/components/browse/BrowseAutomatedCardGroup.spec.js
- packages/portal/tests/unit/components/entity/EntityTable.spec.js
- packages/portal/tests/unit/server-middleware/api/cache/index.spec.js
* Extends cache server middleware to support retrieval of multiple cache entries in one request, by requesting `/_api/cache`, with one or more `id` query parameters, e.g. `/_api/cache?id=items/type-counts&id=items/recent`
* Keeps support of individual cache entries via e.g. `/_api/cache/items/recent`
* Cache server middleware responses are now always objects with each property keyed by the ID
> feat: fetch multiple cache entries

- packages/contentful/migrations/0104-create-embed-header-conent-type.cjs
- packages/contentful/migrations/0104-create-embed-section-content-type.cjs
- packages/contentful/migrations/0105-link-to-hash-fragment.cjs
- packages/portal/src/components/landing/LandingEmbed.vue
- packages/portal/src/components/landing/LandingHero.vue
- packages/portal/src/components/landing/LandingImageCardGroup.vue
- packages/portal/src/components/landing/LandingInfoCardGroup.vue
- packages/portal/src/components/landing/LandingPage.vue
- packages/portal/src/modules/contentful/queries/browse-landing-static-page.graphql
- packages/portal/tests/size/.size-limit.json
- packages/portal/tests/unit/components/landing/LandingEmbed.spec.js
- packages/portal/tests/unit/components/landing/LandingImageCardGroup.spec.js
- packages/portal/tests/unit/components/landing/LandingInfoCardGroup.spec.js
- Migration to create `embedSection` content type to be able to create a section with a title, text and background image to accompany an embed
- Adds new component `LandingEmbed`
- Use `b-col` for header sections to have smaller, better readable text columns on desktop.
> feat: landing embed

- packages/portal/src/components/download/DownloadButton.vue
- packages/portal/src/components/search/SearchInterface.vue
- packages/portal/src/pages/media/index.vue
- packages/portal/src/plugins/apis.js
- packages/portal/src/plugins/europeana/annotation.js
- packages/portal/src/plugins/europeana/entity-management.js
- packages/portal/src/plugins/europeana/entity.js
- packages/portal/src/plugins/europeana/recommendation.js
- packages/portal/src/plugins/europeana/record.js
- packages/portal/src/plugins/europeana/search.js
- packages/portal/src/plugins/europeana/set.js
- packages/portal/src/plugins/europeana/thumbnail.js
- packages/portal/src/plugins/europeana/utils.js
- packages/portal/src/store/index.js
- packages/portal/tests/unit/components/download/DownloadButton.spec.js
- packages/portal/tests/unit/components/search/SearchInterface.spec.js
- packages/portal/tests/unit/pages/media/index.spec.js
- packages/portal/tests/unit/plugins/apis.spec.js
- packages/portal/tests/unit/plugins/europeana/annotation.spec.js
- packages/portal/tests/unit/plugins/europeana/entity-management.spec.js
- packages/portal/tests/unit/plugins/europeana/entity.spec.js
- packages/portal/tests/unit/plugins/europeana/recommendation.spec.js
- packages/portal/tests/unit/plugins/europeana/record.spec.js
- packages/portal/tests/unit/plugins/europeana/search.spec.js
- packages/portal/tests/unit/plugins/europeana/set.spec.js
- packages/portal/tests/unit/plugins/europeana/thumbnail.spec.js
- packages/portal/tests/unit/store/index.spec.js
* extends apis store `init` mutation to set API base URLs from, in order of preference: custom request headers; environment variables; defaults
* modifies API plugin initialisation to treat the apis store as the authority for base URLs
* modifies components and pages to refer to the apis store for API URLs instead of the config
* fixes the lookup of the custom request headers for APIs with camel-cased IDs, e.g. entityManagement, iiifPresentation, by kebab-casing them for the header name
> refactor: store preferred API base URLs

- packages/portal/nuxt.config.js
- packages/portal/src/server-middleware/api/events/log.js
- packages/portal/src/server-middleware/api/events/pg.js
- packages/portal/src/server-middleware/api/events/trending.js
- packages/portal/src/server-middleware/api/utils.js
- packages/portal/tests/size/.size-limit.json
- packages/portal/tests/unit/server-middleware/api/events/log.spec.js
- packages/portal/tests/unit/server-middleware/api/events/pg.spec.js
- packages/portal/tests/unit/server-middleware/api/events/trending.spec.js
* Moves events server middleware code responsible for connecting to postgres into a single file
* Uses postgres connection pool, the max clients of which can be specified by env var `POSTGRES_MAX`, defaulting to 10
* Makes events server middlewares use this shared pg-connecting code
> refactor: use postgres connection pool

- packages/portal/src/components/search/SearchQueryOptions.vue
- packages/portal/tests/unit/components/search/SearchQueryOptions.spec.js
Issue: Listening to `focusout` event and checking for the `relatedTarget` is not working in all browsers. `relatedTarget` defines the secondary event target (the element receiving focus). But whether an element receives focus is browser specific. For example Safari and browsers on iOS do not set the focus state on buttons, leaving `relatedTarget` set to `null`.
Fix: Refactored to use `click` and `focusin` events and check the event’s `target`.
> Fix: search dropdown options unreachable Safari/iOS

- packages/portal/src/mixins/logEvent.js
- packages/portal/src/pages/item/_.vue
- packages/portal/tests/unit/mixins/logEvent.spec.js
- packages/portal/tests/unit/pages/item/_.spec.js
- packages/vue-session/src/manager.js
- packages/vue-session/src/monitor.js
- packages/vue-session/src/session.js
- packages/vue-session/tests/manager.spec.js
- packages/vue-session/tests/session.spec.js
* vue-session package:
* Add a getter `isActive` to Session class instances, indicating whether the session is active
* When Manager class instance instantiates a session, it is by default not marked as active
* Sessions are only marked as active when Monitor class instance observes one of the monitored events and calls the callback, touching the session
* Sessions are not considered active if they have expired
* Sessions accessed via the manager are reactive in Vue, so may be used in watchers and computed properties
* logEvent mixin:
* only log event if session is active
* return true/false indicating if event was logged
* item page:
* do not (attempt to) log view event until session is active
> feat: sessions inactive until monitored event

- packages/portal/src/components/item/ItemHero.vue
- packages/portal/src/mixins/advancedSearch.js
- packages/portal/tests/unit/components/item/ItemHero.spec.js
In the search query passed to the IIIF viewer, include any terms from `fulltext contains` advanced search rules.
> fix: pass fulltext query terms to IIIF viewer

- docker/compose/postgres/model/06-clean-up-duplicate-events-actions.psql
- packages/portal/src/mixins/logEvent.js
- packages/portal/tests/unit/mixins/logEvent.spec.js
Before the initial request is complete, the `eventMayBeLogged` watcher will also trigger and send another identical request, i.e. before `eventLogged` has been set to `true`. Prevent this via an additional progress-monitoring boolean, `eventBeingLogged`.
SQL migration to clean up, and prevent recurrence, to be run **after** code deployment.
> fix: prevent duplicate event log requests

- packages/portal/src/components/content/ContentPrimaryCallToAction.vue
- packages/portal/src/components/home/HomeHero.vue
- packages/portal/src/components/landing/LandingCallToAction.vue
- packages/portal/src/components/landing/LandingPage.vue
- packages/portal/src/modules/contentful/queries/browse-landing-static-page.graphql
- packages/portal/src/pages/microsite/DS4CH.eu.vue
- packages/portal/tests/unit/components/content/ContentPrimaryCallToAction.spec.js
- packages/portal/tests/unit/components/landing/LandingCallToAction.spec.js
- packages/style/scss/DS4CH/style.scss
- packages/style/scss/responsive-background-image.scss
- Adds the primary CTA title to be (conditionally) displayed as an h2
- Adds a responsive background image to the LandingCallToAction component with separate styling for the 'Twin it!'/3D background
- Fixes responsive background styles for wqhd and 4k  breakpoints (also for home hero)
> feat: DS4CH variant landing call to action

- packages/portal/src/components/landing/LandingPage.vue
- packages/portal/src/mixins/parity.js
- packages/portal/tests/unit/mixins/parity.spec.js
* new parity mixin with `markParity` method which accepts an HTML class name as its param
* when called, gets all elements with the class name, detects if they are odd or even occurrences of the class name, and adds a data attribute to them, `data-parity` with either "odd" or "even"
* called when LandingPage is mounted, for the image-card class
> feat: mixin to mark element parity

- packages/portal/nuxt.config.js
- packages/portal/src/components/browse/BrowsePage.vue
- packages/portal/src/components/home/HomePage.vue
- packages/portal/src/pages/index.vue
- packages/portal/tests/size/.size-limit.json
- packages/portal/tests/unit/components/home/HomePage.spec.js
- packages/portal/tests/unit/pages/index.spec.js
* mv the logic for home page retrieval and display from pages/home/index.vue to components/home/HomePage.vue
* make the catch-all pages/index.vue detect when there is no slug in the route and render HomePage
* DRY up the browse/static/landing page logic in pages/index.vue
* stop using a random image from the home page image set for the social media image as it should always have a specific one set
* rm redundant slug property from index page
> refactor: mv home page to component

- packages/contentful/migrations/0128-add-size-image-profile.cjs
- packages/portal/src/components/DS4CH/DS4CHLandingHero.vue
- packages/portal/src/components/generic/StackedCardsSwiper.vue
- packages/portal/src/components/home/HomeHero.vue
- packages/portal/src/components/landing/LandingCallToAction.vue
- packages/portal/src/components/landing/LandingHero.vue
- packages/portal/src/components/landing/LandingIllustrationGroup.vue
- packages/portal/src/components/landing/LandingImageCard.vue
- packages/portal/src/modules/contentful/templates/assets.js
- packages/portal/tests/unit/components/landing/LandingImageCard.spec.js
- packages/style/scss/responsive-background-image.scss
- Adds a CTF migration to add the 4k+ size to the image display profile
- Adds an additional size for the 4k and up breakpoint to all srcsets and background image CSS vars
- Fix the home hero background position to center the image
- Clean up LandingImageCard  ('pro' variant) image styles
> refactor: fix responsive images

- .github/workflows/ci.yml
- package-lock.json
- packages/portal/package.json
- packages/portal/src/cachers/collections/organisations.js
- packages/portal/src/components/entity/EntityTable.vue
- packages/portal/src/components/generic/PaginationNavInput.vue
- packages/portal/src/components/generic/SmartLink.vue
- packages/portal/src/components/search/SearchQueryOptions.vue
- packages/portal/src/components/stories/StoriesTagsDropdown.vue
- packages/portal/src/lang/en.js
- packages/portal/src/pages/collections/_type/_.vue
- packages/portal/src/pages/collections/_type/index.vue
- packages/portal/tests/size/.size-limit.json
- packages/portal/tests/unit/cachers/collections/organisations.spec.js
- packages/portal/tests/unit/components/entity/EntityTable.spec.js
- packages/style/scss/form.scss
- packages/style/scss/table.scss
- Updates the organisations cacher to retrieve the country from entity API and manipulate the value to a prefLabel: 
- Production entity API returns a country code: uses `i18n-iso-countries` to get prefLabels. (no Maltese (mt) support)
- Acceptance entity API returns entity URI. Does a prefLabel look up for each country
- Localises the country prefLabel
- Adds search/filter feature to the EntityTable
- Adds pagination to the EntityTable
- Adds the country column for organisations type table
- Adds a row details slot for organisations type table to toggle display of (more) data on smaller screens
- Saves and applies the filter, sort and page queries in the URL
- Updates the search form styles (reused on Stories page)
- Prevents URL query parameters from Stories and collections type pages …
> feat: institutions page

- packages/portal/src/components/content/ContentCard.vue
- packages/portal/src/components/entity/EntityHeader.vue
- packages/portal/src/components/item/ItemSummaryInfo.vue
- packages/portal/src/components/metadata/MetadataField.vue
- packages/portal/src/lang/en.js
- packages/portal/src/mixins/truncate.js
- packages/portal/src/plugins/europeana/search.js
- packages/portal/src/plugins/vue-filters.js
- packages/portal/src/server-middleware/api/jira-service-desk/feedback.js
- packages/portal/src/server-middleware/api/jira-service-desk/galleries.js
- packages/portal/tests/unit/components/metadata/MetadataField.spec.js
- packages/portal/tests/unit/mixins/truncate.spec.js
* in prep for Vue 3, which has no filters
* add unit tests, which filter didn't have
* drop the ellipsis and list separator formatting strings from the English lang file, as the other UI languages all just have the same symbol anyway
> refactor: mv truncate filter to a mixin

- packages/portal/src/cachers/collections/organisations.js
- packages/portal/src/pages/collections/_type/_.vue
- packages/portal/src/plugins/europeana/entity.js
- packages/portal/tests/unit/cachers/collections/organisations.spec.js
- packages/portal/tests/unit/plugins/europeana/entity.spec.js
The old entity URI is included in the sameAs property when retrieving the new entity data, so include the sameAs Europeana entity URI in:
1. Searches for items on the organisation entity collection page
2. Cached counts of items associated with the organisation entity, for the institutions page
Also DRY up the entity plugin by declaring entity types in a constant.
> chore: handle updated organisation entity URIs

- packages/portal/src/cachers/collections/index.js
- packages/portal/tests/unit/cachers/collections/index.spec.js
Entity API search pagination is due to be changed from starting at 0 to starting at 1.
Refactor our entity caching code to not explicitly request the page and increment it, but instead don’t specify it in the first request, then rely on the `next` property in the subsequent responses, which contains the URL of the next page in the set.
Doing so means that it will work with both scenarios, first page being 0 or 1, without the need for e.g. a feature toggle to switch between the two.
> refactor: paginate over entities via `next` in response

- packages/portal/src/components/entity/EntityBadges.vue
- packages/portal/src/components/entity/EntityCardGroup.vue
- packages/portal/src/pages/item/_.vue
- packages/portal/src/plugins/europeana/entity.js
- packages/portal/tests/unit/pages/item/_.spec.js
- packages/portal/tests/unit/plugins/europeana/entity.spec.js
As it's aware of old entity IDs.
It does not support field specification like the search method, so use lodash's pick to store only the needed fields.
> refactor: use entity retrieve method to find entities

- packages/portal/src/components/item/ItemPinModal.vue
- packages/portal/src/i18n/lang/en.js
- packages/portal/src/mixins/europeana/entities/entityBestItemsSet.js
- packages/portal/tests/unit/mixins/europeana/entities/entityBestItemsSet.spec.js
- uses the retrieved entity IDs for proper organisation entity handling
- Removes the `set.entityBestBets.title` string. That was used to create an entity best set title for each locale, but does not work as expected due to lazy loading of the i18n locales. That makes it impossible to access the string for each locale. Besides it does not really add any value to the title.
> fix: use retrieved entity ids as set keys

- packages/portal/src/components/home/HomeLatestStories.vue
- packages/portal/src/components/related/RelatedEditorial.vue
- packages/portal/src/components/stories/StoriesInterface.vue
- packages/portal/src/features/toggles.js
- packages/portal/src/middleware/redirects.js
- packages/portal/src/modules/contentful/queries/entity-related-content.graphql
- packages/portal/src/modules/contentful/queries/latest-editorial-content.graphql
- packages/portal/src/modules/contentful/queries/related-content.graphql
- packages/portal/src/modules/contentful/queries/stories-by-sys-id.graphql
- packages/portal/src/modules/contentful/queries/stories-minimal.graphql
- packages/portal/src/modules/contentful/queries/theme-related-content.graphql
- packages/portal/src/utils/contentful/entry-url.js
- packages/portal/tests/unit/components/home/HomeLatestStories.spec.js
- packages/portal/tests/unit/components/related/RelatedEditorial.spec.js
- packages/portal/tests/unit/components/stories/StoriesInterface.spec.js
- packages/portal/tests/unit/middleware/redirects.spec.js
- packages/portal/tests/unit/utils/contentful/entry-url.spec.js
* add feature toggle `redirectBlogsToStories`, enabled with `ENABLE_REDIRECT_BLOGS_TO_STORIES=1`
* extend redirect middleware to redirect /blog to /stories and /blog/X to /stories/X, behind feature toggle
* add a utility helper function to get Contentful entry URLs, and make components use it, to DRY them up
* update Contentful GraphQL queries to conditionally retrieve either blogPosting or story entries, and have calling pages/components pass the state of the feature toggle to determine which is retrieved and displayed
> feat: redirect blog posts to stories

- packages/portal/src/components/story/StoryPost.vue
i.e. not sometimes as though the subtitle
> refactor: show story post description always beneath image

- packages/portal/src/components/image/ImageWithAttribution.vue
- packages/portal/src/components/story/StoryHero.vue
Only seems to cause issues on Safari, where the `object-fit` style causes the image to be cropped.
Caused by https://github.com/europeana/portal.js/pull/2047/commits/c3712a0579765aceb1c73f9b08e44712d0e0091b#diff-5afef1e4d9003ec3829eb5c49b3d10b26dc48b34ebb9f586327462c8900d6aa4
> fix: do not crop image with attribution sections

- packages/portal/.env.example
- packages/portal/nuxt.config.js
- packages/portal/src/components/generic/NewFeatureNotification.vue
- packages/portal/src/features/README.md
- packages/portal/src/features/index.js
- packages/portal/src/features/notifications.js
- packages/portal/src/i18n/lang/en.js
- packages/portal/src/layouts/default.vue
- packages/portal/tests/unit/components/generic/NewFeatureNotification.spec.js
- packages/portal/tests/unit/features/index.spec.js
- packages/portal/tests/unit/features/notifications.spec.js
- packages/portal/tests/unit/layouts/default.spec.js
* permit restricting feature notifications by UI locale, like `APP_FEATURE_NOTIFICATION_LOCALES=en,nl`
* refactor feature notification display logic to move most of it out of default layout and into `@/features/notifications`
* move the rendering of the notification text into the component, instead of a slot supplied by the default layout
* when the "show me" link in the notification is clicked, hide the toast
* add a feature notification for the immersive stories
> feat: locales for feature notifications

- packages/portal/src/components/browse/BrowseContentCard.vue
- packages/portal/src/components/content/ContentCard.vue
- packages/portal/src/components/content/ContentCardSection.vue
- packages/portal/src/components/content/ContentHubPage.vue
- packages/portal/src/components/home/HomeLatestStories.vue
- packages/portal/src/components/image/ImageOptimised.vue
- packages/portal/src/components/stories/StoriesFeaturedCard.vue
- packages/portal/src/components/stories/StoriesInterface.vue
- packages/portal/tests/unit/components/content/ContentCard.spec.js
- packages/portal/tests/unit/components/content/ContentHubPage.spec.js
- packages/style/scss/cards.scss
- handles content card image optimisation for Contentful images in `ContentCard` component. This instead of setting it per `ContentCard` instance.
- Simplifies setting the card image width and height. `ContentCard`s that are not in the masonry layout all have a set height (13rem) and max-width (480px) for default cards. List and mini cards also have set dimensions. Only `ItemPreviewCards` need to pass the image's intrinsic sizes
- adds default image crop settings including face focus for the card image
- adds custom image crop settings for StoriesFeaturedCard
> refactor: optimise content card image

- README.md
- docker-compose.app.yml
- docker-compose.yml
- packages/portal/Dockerfile
1. Adds a a new Docker Compose YAML file to run the app along with the rest of the services.
Run with `docker compose -f docker-compose.app.yml up`
App will be exposed on port 8080 on the host.
Example: run with different published image tags:
```sh
TAG=1.154.0 docker compose -f docker-compose.app.yml up
TAG=1.155.0 docker compose -f docker-compose.app.yml up
```
2. Adds IIIF_PRESENTATION_PLUGIN as a build argument for the app Docker image.
Example: build & run local branch with different IIIF Presentation plugins:
```sh
IIIF_PRESENTATION_PLUGIN=mirador TAG=${IIIF_PRESENTATION_PLUGIN} \
docker compose -f docker-compose.app.yml up --build
IIIF_PRESENTATION_PLUGIN=list-props TAG=${IIIF_PRESENTATION_PLUGIN} \
docker compose -f docker-compose.app.yml up --build
```
> chore: separate Docker Compose file to run app

- package-lock.json
- packages/portal/jest.config.js
- packages/portal/nuxt.config.js
- packages/portal/package.json
- packages/portal/src/components/generic/StackedCardsSwiper.vue
- packages/portal/src/components/item/ItemMediaSwiper.vue
- packages/portal/src/components/landing/LandingIllustrationGroup.vue
- packages/portal/src/i18n/lang/en.js
- packages/portal/src/mixins/swiper.js
- packages/portal/tests/unit/mixins/swiper.spec.js
- Updates the Swiper package to the latest version 11.1.5
- `Lazy` no longer is a separate Swiper module but relies on native image lazy loading
- `A11y` module is introduced
- Adds translation strings for Swiper a11y labels
- Updates all swiper instances to work with the new version (StackedCardsSwiper, LandingIllustrationGroup, ItemMediaSwiper)
- Refactor StackedCardsSwiper to use ImageOptimised
> chore: update swiper package

- packages/portal/src/components/entity/EntityBadges.vue
- packages/style/scss/badges.scss
To prevent badges with long text values from breaking the layout.
> fix: max width on entity badges

- packages/portal/src/components/search/SearchQueryBuilderRuleTermInput.vue
- packages/portal/src/components/stories/StoriesTagsDropdown.vue
`aria-expanded` is not allowed on element with role `searchbox`.
This is a workaround to let the e2e tests pass.
Proper solution will need a refactor of the searchbox into a combobox with correct child elements and roles. WIP: [#2433 ](https://github.com/europeana/portal.js/pull/2433)
> fix: workaround to not have aria-expanded on searchbox

- package-lock.json
- packages/portal/nuxt.config.js
- packages/portal/package.json
- packages/portal/src/components/search/SearchInterface.vue
- packages/portal/src/components/stories/StoriesInterface.vue
- packages/portal/src/composables/scrollTo.js
- packages/portal/src/pages/collections/persons-or-places.vue
- packages/portal/src/pages/galleries/index.vue
- packages/portal/src/plugins/vue-scrollto.client.js
- packages/portal/tests/unit/components/search/SearchInterface.spec.js
- packages/portal/tests/unit/components/stories/StoriesInterface.spec.js
- packages/portal/tests/unit/composables/scrollTo.spec.js
- packages/portal/tests/unit/pages/collections/persons-or-places.spec.js
* adds a new Vue composable for scrolling to an element, or scrolling so that an element is centred in its container
* the composable will keep a queue of scroll requests and do one at a time, with a pause of 300 ms between, and only permitting each element to be on the queue once at a time
* replaces the use of vue-scrollto plugin with this composable
> feat: add scrollTo composable

- packages/portal/src/components/download/DownloadButton.vue
- packages/portal/src/components/generic/SmartLink.vue
- packages/portal/src/components/item/ItemLanguageSelector.vue
- packages/portal/src/components/item/ItemRecommendations.vue
- packages/portal/src/components/page/PageNavigation.vue
- packages/portal/src/components/search/SearchResultsContext.vue
- packages/portal/src/components/set/SetPublicationRequestWidget.vue
- packages/portal/tests/unit/components/download/DownloadButton.spec.js
as it's the default and thus redundant
> chore: no target "_self" on anchor elements

- packages/portal/src/components/generic/SmartLink.vue
- packages/portal/src/components/item/ItemMediaSwiperThumbnail.vue
- packages/portal/src/components/media/MediaCardImage.vue
- packages/portal/src/components/metadata/MetadataField.vue
- packages/portal/tests/unit/components/media/MediaCardImage.spec.js
to reduce page weight from repeated data-v- attributes and use nested css selectors instead
also remove a data-qa attribute for same reason
> chore: unscope style in repeated components

- packages/portal/src/components/iiif/IIIFMiradorViewer.vue
- packages/portal/src/components/item/ItemHero.vue
- packages/portal/src/components/item/ItemMediaLegacy.vue
- packages/portal/src/components/item/ItemMediaPresentation.vue
- packages/portal/src/components/item/ItemMediaSwiper.vue
- packages/portal/src/pages/item/_.vue
- packages/portal/tests/unit/components/iiif/IIIFMiradorViewer.spec.js
- packages/portal/tests/unit/components/item/ItemHero.spec.js
- packages/portal/tests/unit/components/item/ItemMediaSwiper.spec.js
- packages/portal/tests/unit/pages/item/_.spec.js
as the IIIF manifest will be used anyway, and this greatly reduces page weight from hydration data on items with large numbers of web resources.
also update the mirador viewer to emit an event when selected, instead of using the window message posting left over from when iframe was in use.
align the select event on the item media components to use an object which represents the full web resource, not just an id.
> refactor: don't store media on item page when IIIF

- packages/portal/src/components/item/ItemMediaThumbnails.vue
- packages/portal/tests/unit/components/item/ItemMediaThumbnails.spec.js
to prevent browser loading all in-between images while smooth scrolling
> refactor: instant scroll on mounted

- packages/portal/src/components/item/ItemMediaPresentation.vue
- packages/portal/src/components/item/ItemMediaSidebar.vue
- packages/portal/src/components/item/ItemMediaThumbnails.vue
- packages/portal/src/components/media/MediaAnnotationList.vue
- packages/portal/src/composables/itemMediaPresentation.js
- packages/portal/tests/unit/components/item/ItemMediaPresentation.spec.js
- packages/portal/tests/unit/components/item/ItemMediaSidebar.spec.js
- packages/portal/tests/unit/components/item/ItemMediaThumbnails.spec.js
- packages/portal/tests/unit/components/media/MediaAnnotationList.spec.js
- packages/portal/tests/unit/composables/itemMediaPresentation.spec.js
with global refs and computed properties for current item's media presentation, to be shared by components that use it
following the pattern from [Vue.js - State Management](https://vuejs.org/guide/scaling-up/state-management.html#simple-state-management-with-reactivity-api)
* alleviates prop drilling
* acts as SSOT for media presentation data provision
* reduces data manipulation logic in components
> refactor: create useItemMediaPresentation composable

- package-lock.json
- packages/portal/jest.config.js
- packages/portal/package.json
- packages/portal/src/components/iiif/IIIFMiradorViewer.vue
- packages/portal/src/components/item/ItemHero.vue
- packages/portal/src/components/item/ItemMediaLegacy.vue
- packages/portal/src/components/item/ItemMediaPresentation.vue
- packages/portal/src/components/item/ItemMediaSidebar.vue
- packages/portal/src/components/item/ItemMediaSwitch.vue
- packages/portal/src/components/item/ItemPreviewCard.vue
- packages/portal/src/components/item/ItemPreviewCardGroup.vue
- packages/portal/src/components/media/MediaAnnotationList.vue
- packages/portal/src/components/media/MediaAnnotationSearch.vue
- packages/portal/src/components/media/MediaImageViewer.vue
- packages/portal/src/composables/activeTab.js
- packages/portal/src/composables/itemMediaPresentation.js
- packages/portal/src/i18n/lang/en.js
- packages/portal/src/utils/europeana/media/AnnotationList.js
- packages/portal/src/utils/europeana/media/Base.js
- packages/portal/src/utils/europeana/media/SearchHit.js
- packages/portal/tests/size/.size-limit.json
- packages/portal/tests/unit/components/iiif/IIIFMiradorViewer.spec.js
- packages/portal/tests/unit/components/item/ItemHero.spec.js
- packages/portal/tests/unit/components/item/ItemMediaSidebar.spec.js
- packages/portal/tests/unit/components/item/ItemPreviewCard.spec.js
- packages/portal/tests/unit/components/item/ItemPreviewCardGroup.spec.js
- packages/portal/tests/unit/components/media/MediaAnnotationList.spec.js
- packages/portal/tests/unit/components/media/MediaAnnotationSearch.spec.js
- packages/portal/tests/unit/composables/activeTab.spec.js
- packages/portal/tests/unit/composables/itemMediaPresentation.spec.js
Composables:
* update `itemMediaPresentation`:
* add support for searching annotations via the IIIF Search API service on the Presentation manifest, and storing results and hits in new refs
* add a new ref for the active annotation
* create `activeTab`:
* helper for when using Bootstrap Vue tab to pre-select the active tab based on the hash in the route, and to update the route hash when the active tab changes
* keeps a history of the active tabs, to aid in not re-fetching data after it's been cached once but the tab becomes inactive
Components:
* update `ItemHero`:
* stop computing the full text query and prop-drilling it down from here
* update `ItemMediaPresentation`:
* stop handling annotation updates, which annotation components should do directly via `useItemMediaPresentation` …
> feat: item media annotation search

- packages/portal/src/components/item/ItemMediaThumbnails.vue
- packages/portal/tests/unit/components/item/ItemMediaThumbnails.spec.js
- Introduces lazy loading / infinite scrolling of the item media thumnbnails
- Renders max 5 thumbnails on initial load
- When there are more it prepends or appends an extra `li` as skeleton for the non-rendered thumbnails
- observes when the skeleton is intersected to load more (`perPage`, set to 5) thumbnails, using the IntersectionObserver API
> feat: lazy load thumbnail list elements using IntersectionObserver

- packages/portal/src/components/item/ItemMediaPresentation.vue
- packages/portal/src/components/media/MediaCardImage.vue
- packages/portal/src/components/media/MediaImageViewer.vue
- packages/portal/src/composables/itemMediaPresentation.js
- packages/portal/src/utils/europeana/media/Base.js
- packages/portal/src/utils/europeana/media/Presentation.js
- packages/portal/src/utils/europeana/media/Resource.js
- packages/portal/src/utils/europeana/media/Service.js
- packages/portal/tests/unit/components/media/MediaImageViewer.spec.js
- packages/portal/tests/unit/composables/itemMediaPresentation.spec.js
- packages/portal/tests/unit/utils/europeana/media/Presentation.spec.js
- packages/portal/tests/unit/utils/europeana/media/Resource.spec.js
- packages/portal/tests/unit/utils/europeana/media/Service.spec.js
* add new europeana/media utils classes to represent resources (e.g. image/audio/etc) and services (e.g. IIIF Image service)
* both include conversion to/from EDM equivalents
* move retrieval of IIIF Image info.json out of MediaImageViewer component and into new service class
* make MediaCardImage aware of both WebResource and EuropeanaMediaResource classes for its media prop
> refactor: add resource and service media classes

- packages/portal/src/components/generic/AlertMessage.vue
- packages/portal/src/pages/feature-ideas/index.vue
- packages/portal/tests/unit/components/browse/BrowseAutomatedCardGroup.spec.js
- packages/portal/tests/unit/components/embed/EmbedHTML.spec.js
- packages/portal/tests/unit/components/embed/EmbedOEmbed.spec.js
- packages/portal/tests/unit/components/entity/EntityRelatedCollectionsCard.spec.js
- packages/portal/tests/unit/components/entity/EntityTable.spec.js
- packages/portal/tests/unit/components/generic/FeatureIdeas.spec.js
- packages/portal/tests/unit/components/home/HomePage.spec.js
- packages/portal/tests/unit/components/item/ItemMediaPresentation.spec.js
- packages/portal/tests/unit/components/item/ItemRecommendations.spec.js
- packages/portal/tests/unit/components/item/ItemTrendingItems.spec.js
- packages/portal/tests/unit/components/media/MediaAnnotationList.spec.js
- packages/portal/tests/unit/components/media/MediaImageViewer.spec.js
- packages/portal/tests/unit/components/related/RelatedCollectionsCard.spec.js
- packages/portal/tests/unit/components/search/SearchFacetDropdown.spec.js
- packages/portal/tests/unit/components/search/SearchInterface.spec.js
- packages/portal/tests/unit/components/set/SetRecommendations.spec.js
- packages/portal/tests/unit/components/stories/StoriesInterface.spec.js
- packages/portal/tests/unit/components/user/UserSets.spec.js
- packages/portal/tests/unit/pages/feature-ideas/index.spec.js
- packages/portal/tests/unit/utils.js
so that:
* fetchState does not need to be repeatedly mocked in component/page unit tests
* it behaves like it does when running the nuxt app
> test: mock nuxt fetchState in mounter

- packages/portal/src/components/item/ItemHero.vue
- packages/portal/src/pages/item/_.vue
- packages/portal/tests/size/.size-limit.json
ItemPage:
* keep WR-level edm:rights only if different from item-level, to save memory
* for IIIF items, keep only ID and edm:rights for WRs as other metadata derived from IIIF
ItemHero:
* when selecting media, including on component creation, combine the emitted resource (from ItemMediaPresentation), and the stored metadata from the prop, so that both IIIF and Record API metadata can be combined where needed, such as for edm:rights here
> fix: restore WR-level rights statement

- packages/portal/src/components/media/MediaImageViewer.vue
temporary workaround to alleviate it messing with zooming/panning tile sources like IIIF
later could be reconsidered if there is a better option as some IIIF images can be slow to load so the loading spinner may still be of value in those scenarios
> refactor: loading spinner for static images only

- packages/portal/src/components/item/ItemMediaPresentation.vue
- packages/portal/src/components/item/ItemMediaSidebar.vue
- packages/portal/src/composables/activeTab.js
- packages/portal/tests/unit/composables/activeTab.spec.js
1. when opening an item page with any sidebar content, #links is always added to the url if there is a IIIF manifest but no annotations or anno search, but this is undesirable if the sidebar is not open
2. back/forward browser navigation goes between tabs on item page before going back to e.g. search results
activeTab composable:
* don't watch activeTabIndex by default, but return a function to start watching on-demand, plus one to [stop watching](https://vuejs.org/guide/essentials/watchers.html#stopping-a-watcher)
* switch to using router replace so that browser back/forward navigation doesn't loop through the tabs 
ItemMediaSidebar:
* add a `show` prop to control visibility
* only watch activeTabIndex changes when component is shown (according to that prop)
* preventing immediate …
> refactor: improve activeTab URL modifications

- packages/portal/src/components/item/ItemMediaPaginationToolbar.vue
- packages/portal/src/components/item/ItemMediaPresentation.vue
- Fixes style bug on older Chrome (v70) and iOS where the mock fullscreen styles were not applied as expected
- Includes the sidebar toggle in fullscreen mode, when there is sidebar content, on mobile and tablet size screens
> fix: fullscreen on ipad

- packages/portal/src/components/item/ItemMediaPresentation.vue
- packages/portal/src/components/item/ItemMediaSidebar.vue
- packages/portal/src/composables/activeTab.js
- ensure any active tab is added to hash when sidebar first opened, inc. #links
- clear hash when sidebar closed
- don't show sidebar if other non-sidebar hash is set, e.g. for API requests w/ #api-requests
> fix: activeTab add/remove hash

- packages/portal/src/components/media/MediaImageViewer.vue
because the annotations watcher may fire before the map is initialised
> fix: nullish check on ol Map when highlighting

- packages/portal/src/components/item/ItemMediaPresentation.vue
so that media error can be cleared when switching page where a different media resource would be loaded
> refactor: separate media error from fetch error

- packages/portal/src/components/media/MediaImageViewer.vue
* show the loading spinner as soon as the viewer component starts fetching, i.e. also during iiif info.json retrieval and initial load of iiif or static image
* zooming in or panning a iiif image will not bring the spinner back
* changing the page will bring the spinner back
* also clear all the layers from the ol map while fetching so that old annotations and images from previous pages or items don't hang around
> refactor: loading spinner on initial IIIF image load

- packages/portal/src/components/download/DownloadButton.vue
- packages/portal/src/components/entity/EntityTable.vue
- packages/portal/src/components/generic/LoadingSpinner.vue
- packages/portal/src/components/item/ItemMediaPresentation.vue
- packages/portal/src/components/media/MediaAnnotationList.vue
- packages/portal/src/components/media/MediaImageViewer.vue
- packages/portal/src/components/search/SearchFacetDropdown.vue
- packages/portal/src/components/search/SearchInterface.vue
- packages/portal/src/components/stories/StoriesInterface.vue
- packages/portal/src/components/user/UserSets.vue
- packages/portal/src/pages/account/index.vue
- packages/portal/src/pages/feature-ideas/index.vue
- packages/portal/src/pages/galleries/_.vue
- packages/portal/src/pages/galleries/index.vue
- packages/portal/src/pages/index.vue
- packages/portal/src/pages/item/_.vue
- packages/portal/src/pages/stories/_.vue
- packages/portal/src/pages/stories/index.vue
- packages/portal/src/pages/themes/_.vue
- packages/portal/tests/unit/components/generic/LoadingSpinner.spec.js
- packages/portal/tests/unit/pages/galleries/_.spec.js
- packages/portal/tests/unit/pages/galleries/index.spec.js
- give the loading spinner a configurable root element tag, defaulting to div
- prevent the loading spinner elements rendering at all until its delay has elapsed, to help with CLS on not-too-slow pages/components
- remove all wrapping div, b-container, b-row and b-col elements from around LoadingSpinner in components that use it, and combine any classes from those onto the LoadingSpinner element itself
> refactor: loading spinner configurable tag

- packages/portal/src/mixins/klaro.js
- packages/portal/tests/unit/mixins/klaro.spec.js
For Matomo, tell it to forget cookie consent given.
For Hotjar, the only way to stop it is to reload the page, so do that.
> feat: handle rm hotjar/matomo consent

- .github/workflows/ci.yml
- packages/portal/nuxt.config.js
- packages/portal/src/components/embed/EmbedGateway.vue
- packages/portal/src/components/page/PageCookieConsent.vue
- packages/portal/src/components/page/PageCookiesWidget.vue
- packages/portal/src/layouts/default.vue
- packages/portal/src/layouts/ds4ch.vue
- packages/portal/src/layouts/landing.vue
- packages/portal/src/mixins/klaro.js
- packages/portal/src/pages/item/_.vue
- packages/portal/src/plugins/vue-matomo.client.js
- packages/portal/src/utils/waitFor.js
- packages/portal/tests/size/.size-limit.json
- packages/portal/tests/unit/components/page/PageCookiesWidget.spec.js
- packages/portal/tests/unit/mixins/klaro.spec.js
- packages/portal/tests/unit/pages/item/_.spec.js
- packages/portal/tests/unit/plugins/vue-matomo.client.spec.js
- packages/portal/tests/unit/utils/waitFor.spec.js
instead of in layouts, to prevent passing klaro manager/config down to components, and isolate use of the mixin methods to fewer locations
abstract waitForMatomo function to be a utility function for waiting for arbitrary callbacks to return truthy values, and also use it to have klaro-dependent components wait for it to become available before attempting to work with it
> refactor: use klaro mixin in cookie components

- package-lock.json
- packages/portal/babel.config.cjs
- packages/portal/nuxt.config.js
- packages/portal/package.json
- packages/portal/src/composables/deBias.js
- packages/portal/src/pages/item/_.vue
- packages/portal/tests/unit/composables/deBias.spec.js
- packages/portal/tests/unit/pages/item/_.spec.js
- create a De-Bias composable for filtering and parsing relevant annotations into highlighted terms and their definition, limiting each term to a single field, and limiting to those with definitions in the supplied language
- initialise this on the item page with the item's annotations and the UI locale
- other child components will then be able to use the composable and detect which terms to highlight for a given field with the method `termsToHighlight('dc:title') // => ['offensive']`, and get their definition with the method `definitionOfTerm('offensive')`
> feat: De-Bias composable

- packages/portal/src/components/search/SearchInterface.vue
- packages/portal/src/pages/collections/_type/_.vue
- packages/portal/src/pages/search/index.vue
- packages/portal/tests/unit/components/search/SearchInterface.spec.js
- packages/portal/tests/unit/pages/search/index.spec.js
Simplify the handling of overrides vs local params from the user/URL-constructed query by always favouring the latter over the former.
> refactor: prefer local params over overrides

- packages/portal/src/plugins/error.js
- packages/portal/src/plugins/europeana/apis/base.js
instead of earlier in APIs error handling as intermediaries may need it
> refactor: delete error data in error handler plugin

- packages/portal/src/plugins/europeana/edm/Aggregation.js
To prevent regenerating the data multiple times on the item page.
> perf: memoise EDM Aggregation displayableWebResources

- packages/portal/src/pages/item/_.vue
don't create new instances of WebResource if the source is already an instance of it
> perf: selective WebResource construction

- packages/portal/src/features/toggles.js
- packages/portal/src/pages/item/_.vue
- packages/portal/tests/unit/pages/item/_.spec.js
so that it's always used if the Record api returns 410 Gone
> chore: rm tombstone page feature toggle

- packages/portal/src/features/toggles.js
- packages/portal/src/plugins/europeana/apis/config/context.js
- packages/portal/src/plugins/europeana/apis/config/env.js
- packages/portal/tests/unit/plugins/europeana/apis/config/env.spec.js
so that code within the API client classes can check to see which version of the API they need to work with using `this.config.version`
> chore: store version in APIs config

- packages/portal/src/store/set.js
- packages/portal/tests/unit/store/set.spec.js
because items are re-ordered differently now (see #2600)
> chore: rm redundant item order preservation

- packages/portal/src/components/item/ItemSelectCheckbox.vue
- packages/portal/src/store/set.js
- packages/portal/tests/unit/components/item/ItemSelectCheckbox.spec.js
- packages/portal/tests/unit/store/set.spec.js
Always bases the selected state on the store by making it a computed property.
In order to continue using v-model on the `b-form-checkbox` add a setter to the computed property.
As a result the separate `toggleItemSelection` method isn't needed anymore.
Also added a validation to the set store to not allow the same ID be selected twice.
> refactor: compute selected item state from store

- packages/portal/src/components/item/ItemAddButton.vue
- packages/portal/src/components/item/ItemLikeButton.vue
- packages/portal/src/components/item/ItemRemoveButton.vue
- packages/portal/tests/unit/components/item/ItemAddButton.spec.js
- packages/portal/tests/unit/components/item/ItemLikeButton.spec.js
- packages/portal/tests/unit/components/item/ItemRemoveButton.spec.js
because there is nothing to do
> feat: disable item action buttons if no identifiers

- packages/portal/src/components/user/UserHeader.vue
- packages/portal/src/i18n/lang/en.js
- packages/portal/src/pages/account/api-keys.vue
- packages/portal/src/pages/account/index.vue
- packages/portal/tests/unit/components/user/UserHeader.spec.js
- packages/portal/tests/unit/pages/account/api-keys.spec.js
- move top section from my account page into new UserHeader component
- create skeleton api keys page at /account/api-keys, showing UserHeader and link back to my account page
> feat: create skeleton API keys page

- packages/portal/src/components/item/ItemSelectButton.vue
- packages/portal/src/components/search/SearchMultilingualButton.vue
- packages/portal/tests/unit/components/item/ItemSelectButton.spec.js
- packages/portal/tests/unit/components/search/SearchMultilingualButton.spec.js
Show tooltip on:
- mouse over
- focus
Hide tooltip on:
- click
- touch tab
- exception: multilingual search when not logged in, then do show tooltip on first tab.
- tab beyond button (focusout)
Do not track 'click' on first touch tap.
> fix: multilingual search and item select tooltip handling

- packages/portal/src/pages/account/api-keys.vue
- packages/portal/src/plugins/europeana-apis.js
- packages/portal/src/plugins/europeana/auth.js
- packages/portal/tests/unit/pages/account/api-keys.spec.js
- packages/portal/tests/unit/plugins/europeana/auth.spec.js
and implement fetching & display of user's API keys
Configure with:
```
EUROPEANA_AUTH_API_URL=https://keycloak.acceptance.eanadev.org
```
(This duplicates the OAUTH_ORIGIN setting and will need to be kept aligned for now, which should be refactored.)
> feat: create auth service API plugin

- package-lock.json
- packages/portal/package.json
from v1.77.7 deprecation warnings are issued re https://sass-lang.com/d/mixed-decls
> chore: update & lock sass to v1.77.6

- packages/portal/src/composables/activeTab.js
the new hash should still be propagated to the route if known
> fix: don't exit if previous hash unknown

- packages/portal/src/components/user/UserSets.vue
- packages/portal/src/composables/activeTab.js
- packages/portal/src/pages/account/index.vue
- packages/portal/tests/unit/composables/activeTab.spec.js
- packages/portal/tests/unit/pages/account/index.spec.js
- extend activeTab composable to also support router push (instead of default replace)
- refactor AccountIndexPage to use activeTab composable
> refactor: use activeTab in AccountIndexPage, with router push
